"""Static Chinese/English catalogue served by the management WebUI.

The browser receives this plain-data catalogue before rendering so translation
does not depend on a server-side presentation framework.
"""

# ─── Translation dictionary ────────────────────────────────────────────────
_TRANSLATIONS: dict[str, dict[str, str]] = {
    # ── config_panel.py ──────────────────────────────────────────────────
    "sidebar_caption": {
        "zh": "配置面板",
        "en": "Configuration Panel",
    },
    "save_btn": {
        "zh": "保存所有更改",
        "en": "Save All Changes",
    },
    "reload_btn": {
        "zh": "从磁盘重新加载",
        "en": "Reload from Disk",
    },
    "restart_worker_btn": {
        "zh": "🔄 重启主研究容器",
        "en": "🔄 Restart Worker",
    },
    "restart_worker_sent": {
        "zh": "重启请求已发送；主容器将在几秒内重启并按最新配置重装定时任务。运行中的任务会被自动重新排队。",
        "en": "Restart requested; the worker restarts within seconds and reinstalls the schedule from config. Any running job is re-queued automatically.",
    },
    "restart_worker_failed": {
        "zh": "写入重启请求失败：{err}",
        "en": "Failed to write the restart request: {err}",
    },
    "save_success": {
        "zh": "配置已保存！",
        "en": "Configuration saved!",
    },
    "save_failed": {
        "zh": "保存失败: ",
        "en": "Save failed: ",
    },
    "file_found": {
        "zh": "已找到",
        "en": "Found",
    },
    "file_not_found": {
        "zh": "未找到",
        "en": "Not found",
    },
    "lang_toggle": {
        "zh": "English",
        "en": "中文",
    },
    "auth_setup_title": {"zh": "初始化管理员账户", "en": "Set Up the Administrator Account"},
    "auth_setup_notice": {
        "zh": "首次部署请创建管理员账户。密码只会以加盐哈希保存到 .env；通过公网反向代理访问前，请先在本机完成此步骤。",
        "en": "Create the administrator account for this first deployment. The password is stored only as a salted hash in .env; complete this step locally before exposing the panel through a public reverse proxy.",
    },
    "auth_username": {"zh": "用户名", "en": "Username"},
    "auth_username_invalid": {
        "zh": "用户名需为 3–64 个字符，仅可使用字母、数字、点、下划线和连字符。",
        "en": "Use 3–64 characters: letters, numbers, dots, underscores, or hyphens.",
    },
    "auth_password": {"zh": "密码", "en": "Password"},
    "auth_password_confirm": {"zh": "确认密码", "en": "Confirm password"},
    "auth_password_too_short": {
        "zh": "密码至少需要 6 个字符。",
        "en": "Use at least 6 characters for the password.",
    },
    "auth_create_account": {"zh": "创建管理员账户", "en": "Create administrator account"},
    "auth_skip_intranet": {
        "zh": "仅内网使用，跳过登录",
        "en": "Trusted LAN only: skip sign-in",
    },
    "auth_skip_intranet_notice": {
        "zh": "仅限完全受信任的内网：跳过后可直接修改密钥、任务与备份，请勿通过公网或不受控的反向代理访问。",
        "en": "Use only on a fully trusted LAN: skipping sign-in grants direct access to credentials, tasks, and backups. Do not expose the panel through the public internet or an uncontrolled reverse proxy.",
    },
    "auth_skip_intranet_success": {
        "zh": "已关闭面板登录保护；页面将直接进入配置面板。",
        "en": "Panel sign-in is disabled. Opening the panel now goes directly to configuration.",
    },
    "auth_password_mismatch": {"zh": "两次输入的密码不一致。", "en": "The passwords do not match."},
    "auth_setup_success": {"zh": "管理员账户已创建，请登录。", "en": "Administrator account created. Please sign in."},
    "auth_login_title": {"zh": "登录配置面板", "en": "Sign in to the configuration panel"},
    "auth_login_hint": {"zh": "登录后可查看和修改配置、报告与运行任务。", "en": "Sign in to view or change configuration, reports, and run tasks."},
    "auth_login": {"zh": "登录", "en": "Sign in"},
    "auth_login_failed": {"zh": "用户名或密码错误。", "en": "Incorrect username or password."},
    "auth_retry_wait": {"zh": "登录尝试过于频繁，请在 {seconds} 秒后重试。", "en": "Too many attempts. Try again in {seconds} seconds."},
    "auth_logout": {"zh": "退出登录", "en": "Sign out"},
    "auth_change_password": {"zh": "修改管理员密码", "en": "Change administrator password"},
    "auth_current_password": {"zh": "当前密码", "en": "Current password"},
    "auth_new_password": {"zh": "新密码", "en": "New password"},
    "auth_save_password": {"zh": "保存新密码", "en": "Save new password"},
    "auth_current_password_invalid": {"zh": "当前密码不正确。", "en": "The current password is incorrect."},
    "auth_password_changed": {"zh": "密码已更新，请重新登录。", "en": "Password updated. Please sign in again."},
    "auth_accounts_title": {"zh": "账户管理", "en": "Account Management"},
    "auth_accounts_hint": {
        "zh": "账户可访问完整面板。所有者可管理全部账户；每个账户可自行修改密码。",
        "en": "Accounts have full panel access. The owner manages all accounts; each account can change its own password.",
    },
    "auth_accounts_disabled": {
        "zh": "当前已选择仅内网使用，面板登录保护处于关闭状态。",
        "en": "Trusted-LAN mode is active and panel sign-in is disabled.",
    },
    "auth_account_list_title": {"zh": "现有账户", "en": "Accounts"},
    "auth_account_col_username": {"zh": "用户名", "en": "Username"},
    "auth_account_col_role": {"zh": "权限", "en": "Role"},
    "auth_account_col_current": {"zh": "当前", "en": "Current"},
    "auth_account_role_owner": {"zh": "所有者", "en": "Owner"},
    "auth_account_role_admin": {"zh": "完整权限", "en": "Full access"},
    "auth_account_current": {"zh": "当前登录", "en": "Signed in"},
    "auth_change_own_password": {"zh": "修改我的密码", "en": "Change My Password"},
    "auth_account_add_title": {"zh": "添加账户", "en": "Add Account"},
    "auth_account_add": {"zh": "创建账户", "en": "Create Account"},
    "auth_account_added": {"zh": "账户已创建。", "en": "Account created."},
    "auth_account_target": {"zh": "目标账户", "en": "Target account"},
    "auth_account_reset_title": {"zh": "重置账户密码", "en": "Reset Account Password"},
    "auth_account_reset": {"zh": "重置密码", "en": "Reset Password"},
    "auth_account_reset_done": {"zh": "账户密码已重置。", "en": "Account password reset."},
    "auth_account_remove_title": {"zh": "删除账户", "en": "Delete Account"},
    "auth_account_remove_confirm": {"zh": "确认删除所选账户", "en": "Confirm deletion of the selected account"},
    "auth_account_remove": {"zh": "删除账户", "en": "Delete Account"},
    "auth_account_removed": {"zh": "账户已删除。", "en": "Account deleted."},
    "auth_account_none_secondary": {"zh": "暂无可管理的其他账户。", "en": "No secondary accounts to manage."},
    "auth_account_exists": {"zh": "该用户名已存在。", "en": "That username already exists."},
    "auth_account_limit": {"zh": "最多可创建 20 个账户。", "en": "You can create up to 20 accounts."},
    "auth_account_owner_required": {"zh": "只有所有者可以管理其他账户。", "en": "Only the owner can manage other accounts."},
    "auth_account_not_found": {"zh": "账户不存在或已被删除。", "en": "The account does not exist or was removed."},
    "auth_account_cannot_delete_owner": {"zh": "所有者账户不能删除。", "en": "The owner account cannot be deleted."},
    "auth_account_reset_owner_via_self": {"zh": "请在“修改我的密码”中更新所有者密码。", "en": "Use Change My Password to update the owner password."},
    "auth_account_invalid_registry": {"zh": "账户配置无效，未保存更改。", "en": "The account configuration is invalid; changes were not saved."},
    # Tab labels
    "tab_llm": {"zh": "API", "en": "API"},
    "tab_search": {"zh": "数据源", "en": "Data Sources"},
    "tab_keywords": {"zh": "关键词", "en": "Keywords"},
    "tab_scoring": {"zh": "评分", "en": "Scoring"},
    "tab_notifications": {"zh": "通知", "en": "Notifications"},
    "tab_advanced": {"zh": "高级设置", "en": "Advanced"},
    "tab_reports": {"zh": "报告查看", "en": "Reports"},
    "tab_favorites": {"zh": "收藏与检索", "en": "Favorites & Search"},
    "tab_run_manager": {"zh": "每日推送", "en": "Daily Push"},
    "tab_trend_runner": {"zh": "趋势分析", "en": "Trend Analysis"},
    # Sidebar navigation groups
    "nav_group_run": {"zh": "运行", "en": "RUN"},
    "nav_group_content": {"zh": "内容", "en": "CONTENT"},
    "nav_group_config": {"zh": "配置", "en": "CONFIGURATION"},
    "nav_group_system": {"zh": "系统", "en": "SYSTEM"},
    "nav_daily_research": {"zh": "🚀 每日研究", "en": "🚀 Daily Research"},
    "nav_past_daily": {"zh": "🗓 过去日报", "en": "🗓 Past Daily Reports"},
    "nav_trend_tasks": {"zh": "📈 趋势任务", "en": "📈 Trend Tasks"},
    "nav_queue": {"zh": "📋 队列", "en": "📋 Queues"},
    "nav_logs": {"zh": "📜 日志", "en": "📜 Logs"},
    "nav_reports": {"zh": "📄 报告", "en": "📄 Reports"},
    "nav_favorites": {"zh": "⭐ 收藏", "en": "⭐ Favorites"},
    "nav_paper_search": {"zh": "🔎 检索", "en": "🔎 Search"},
    "nav_analytics": {"zh": "📊 用量统计", "en": "📊 Usage Statistics"},
    "nav_keywords": {"zh": "🔑 关键词", "en": "🔑 Keywords"},
    "nav_data_sources": {"zh": "🧭 数据源", "en": "🧭 Data Sources"},
    "nav_scoring": {"zh": "⚖️ 评分", "en": "⚖️ Scoring"},
    "nav_api": {"zh": "🔌 API", "en": "🔌 API"},
    "nav_notifications": {"zh": "🔔 通知", "en": "🔔 Notifications"},
    "nav_advanced": {"zh": "⚙️ 高级设置", "en": "⚙️ Advanced"},
    "nav_accounts": {"zh": "👤 账户", "en": "👤 Accounts"},
    "nav_backup_sync": {"zh": "☁️ 备份与同步", "en": "☁️ Backup & Sync"},
    "nav_history_tasks": {"zh": "🗂 历史维护", "en": "🗂 History Maintenance"},
    "nav_diagnostics": {"zh": "🩺 运行诊断", "en": "🩺 Run Diagnostics"},
    "rm_auto_refresh": {"zh": "自动刷新", "en": "Auto refresh"},
    "rm_auto_refresh_help": {
        "zh": "开启后，有任务运行时每 5 秒刷新状态、队列与日志尾部；刚点击启动时会短暂检查，任务结束后自动停止刷新。",
        "en": "When enabled, status, queue, and live log tail refresh every 5 seconds while a task runs; it briefly watches a newly submitted launch, then stops automatically when work ends.",
    },
    "rm_live_tail_hint": {
        "zh": "日志尾部 80 行（可滚动）",
        "en": "last 80 log lines (scrollable)",
    },
    "rm_queue_pending": {"zh": "待处理队列", "en": "Pending queue"},
    "rm_queue_failed": {"zh": "失败待重试", "en": "Awaiting retry"},
    "rm_daily_queue_title": {"zh": "每日研究队列", "en": "Daily Research Queue"},
    "rm_queue_page_title": {"zh": "任务队列", "en": "Task Queues"},
    "rm_backfill_queue_title": {"zh": "过去日报队列", "en": "Past Daily Queue"},
    "rm_backfill_queue_empty": {
        "zh": "当前没有过去日报任务。",
        "en": "There are no past daily-report tasks.",
    },
    "rm_backfill_queue_completed": {"zh": "已完成", "en": "Completed"},
    "rm_stop_btn": {"zh": "停止运行", "en": "Stop run"},
    "rm_trigger_state_failed": {
        "zh": "上次请求 {state}{suffix}；详情见运行日志。",
        "en": "Last request {state}{suffix}; see run logs.",
    },
    "rm_trigger_error_summary": {
        "zh": "问题摘要：{summary}",
        "en": "Issue summary: {summary}",
    },
    "rm_trigger_state_succeeded": {
        "zh": "上次面板请求已完成（{mode}）；详情见运行日志。",
        "en": "Last panel request completed ({mode}); see run logs.",
    },
    "rm_trigger_docker_keep": {
        "zh": "为避免丢失主容器尚未消费的请求，Docker 模式不从 WebUI 删除队列文件。",
        "en": "In Docker mode the WebUI does not delete queue files the worker may not have consumed yet.",
    },
    "rm_log_truncated": {
        "zh": "... (省略前 {skipped} 行，仅显示最后 {kept} 行) ...",
        "en": "... ({skipped} earlier lines skipped, last {kept} shown) ...",
    },
    "rm_log_read_failed": {"zh": "读取日志失败", "en": "Failed to read log"},
    "report_show_non_arxiv_help": {
        "zh": "开启后显示所有来源；关闭后仅显示 ArXiv 来源的每日研究报告",
        "en": "Show every source when on; only ArXiv daily reports when off",
    },
    "rm_stop_confirm": {"zh": "确认停止", "en": "Confirm stop"},
    "rm_stop_confirm_hint": {
        "zh": "将向正在运行的进程发送停止信号：已完成阶段保留，未完成论文留队待重试。"
              "仅对 WebUI 触发的运行生效。",
        "en": "Sends a stop signal to the running process: finished stages are "
              "kept and unfinished papers stay queued. WebUI-triggered runs only.",
    },
    "rm_stop_sent": {
        "zh": "停止请求已发送（PID {pids}），几秒内生效。",
        "en": "Stop requested (PID {pids}); takes effect within seconds.",
    },
    "rm_stop_failed": {"zh": "停止请求写入失败: {err}", "en": "Failed to write stop request: {err}"},
    "rm_stop_no_pid": {
        "zh": "未能从锁文件解析出 PID，无法发送停止请求。",
        "en": "No PID parsed from the lock file; cannot request a stop.",
    },
    "rm_status_skipped_busy": {
        "zh": "上次请求未执行：已有相同任务在运行（被运行锁跳过）。",
        "en": "Last request did not run: an identical task was already active.",
    },
    # ── usage.py ────────────────────────────────────────────────────────
    "usage_title": {"zh": "用量统计", "en": "Usage Statistics"},
    "usage_empty": {
        "zh": "暂无用量数据。完成任一涉及 LLM 的任务后，这里会出现统计。",
        "en": "No usage yet. Statistics appear after any task that uses an LLM.",
    },
    "usage_load_failed": {
        "zh": "用量数据读取失败",
        "en": "Failed to load usage data",
    },
    "usage_heatmap_title": {
        "zh": "每日用量热力图（近一年）",
        "en": "Daily usage heatmap (last year)",
    },
    "usage_heatmap_less": {"zh": "少", "en": "Less"},
    "usage_heatmap_more": {"zh": "多", "en": "More"},
    "usage_trend_title": {"zh": "用量趋势", "en": "Usage trend"},
    "usage_range_label": {"zh": "时间段", "en": "Time range"},
    "usage_range_7": {"zh": "近7天", "en": "7 days"},
    "usage_range_30": {"zh": "近30天", "en": "30 days"},
    "usage_range_90": {"zh": "近90天", "en": "90 days"},
    "usage_range_365": {"zh": "近365天", "en": "365 days"},
    "usage_range_all": {"zh": "全部", "en": "All"},
    "usage_prompt_tokens": {"zh": "普通输入 Token", "en": "Non-cached input tokens"},
    "usage_cached_prompt_tokens": {"zh": "缓存输入 Token", "en": "Cached input tokens"},
    "usage_completion_tokens": {"zh": "输出 Token", "en": "Output tokens"},
    "usage_total_tokens": {"zh": "总 Token", "en": "Total tokens"},
    "usage_by_model_title": {"zh": "按模型汇总", "en": "By model"},
    "usage_model": {"zh": "模型", "en": "Model"},
    "usage_today_prompt": {"zh": "当日普通输入 Token", "en": "Today non-cached input tokens"},
    "usage_today_cached_prompt": {"zh": "当日缓存输入 Token", "en": "Today cached input tokens"},
    "usage_today_completion": {"zh": "当日输出 Token", "en": "Today output tokens"},
    "usage_month_total": {"zh": "近30天累计用量", "en": "30-day total usage"},
    "usage_range_totals": {"zh": "所选区间 · 普通输入 {prompt} · 缓存输入 {cached_prompt} · 输出 {completion} · 合计 {total} Token", "en": "Selected range · non-cached input {prompt} · cached input {cached_prompt} · output {completion} · total {total} tokens"},
    "usage_heatmap_tip": {
        "zh": "{date} · {tokens} Token · {runs} 次运行",
        "en": "{date} · {tokens} tokens · {runs} runs",
    },
    "usage_heatmap_none": {"zh": "{date} · 无用量", "en": "{date} · no usage"},
    "usage_week_mon": {"zh": "一", "en": "M"},
    "usage_week_wed": {"zh": "三", "en": "W"},
    "usage_week_fri": {"zh": "五", "en": "F"},
    "usage_week_sun": {"zh": "日", "en": "S"},
    "usage_month_1": {"zh": "1月", "en": "Jan"},
    "usage_month_2": {"zh": "2月", "en": "Feb"},
    "usage_month_3": {"zh": "3月", "en": "Mar"},
    "usage_month_4": {"zh": "4月", "en": "Apr"},
    "usage_month_5": {"zh": "5月", "en": "May"},
    "usage_month_6": {"zh": "6月", "en": "Jun"},
    "usage_month_7": {"zh": "7月", "en": "Jul"},
    "usage_month_8": {"zh": "8月", "en": "Aug"},
    "usage_month_9": {"zh": "9月", "en": "Sep"},
    "usage_month_10": {"zh": "10月", "en": "Oct"},
    "usage_month_11": {"zh": "11月", "en": "Nov"},
    "usage_month_12": {"zh": "12月", "en": "Dec"},
    # ── 报告查看页：随手标记（原收藏偏好页融合）─────────────────────────
    "fav_like": {"zh": "喜欢", "en": "Like"},
    "fav_dislike": {"zh": "不喜欢", "en": "Dislike"},
    "tab_analytics": {"zh": "用量统计", "en": "Usage Statistics"},
    "llm_health_title": {"zh": "LLM 健康", "en": "LLM Health"},
    "llm_health_hint": {
        "zh": "汇总所有真实任务（含历史维护）的 LLM 调用；查看不会发送探针请求，也不会额外消耗 Token。",
        "en": "Summarizes LLM calls from all real tasks, including history maintenance; viewing sends no probe or extra token use.",
    },
    "llm_health_no_data": {
        "zh": "尚无真实 LLM 调用记录。运行需要 LLM 的任务后可在这里查看。",
        "en": "No real LLM calls recorded yet. Run an LLM-backed task to see health here.",
    },
    "llm_health_load_failed": {
        "zh": "无法读取 LLM 健康数据：{}",
        "en": "Could not read LLM health data: {}",
    },
    "llm_health_cheap": {"zh": "低成本 LLM", "en": "Low-Cost LLM"},
    "llm_health_smart": {"zh": "高性能 LLM", "en": "High-Performance LLM"},
    "llm_health_status_ok": {"zh": "成功", "en": "Succeeded"},
    "llm_health_status_failed": {"zh": "失败", "en": "Failed"},
    "llm_health_last_result": {"zh": "最新调用", "en": "Latest call"},
    "llm_health_consecutive_failures": {"zh": "连续失败", "en": "Consecutive failures"},
    "llm_health_recent_success": {"zh": "最近 20 次成功率", "en": "Success rate (last 20)"},
    "llm_health_times": {
        "zh": "最近调用：{event} · 最近成功：{success}",
        "en": "Latest call: {event} · Last success: {success}",
    },
    "llm_health_last_error": {"zh": "最近失败说明（已脱敏）", "en": "Latest failure detail (redacted)"},
    "llm_health_col_model": {"zh": "模型", "en": "Model"},
    "llm_health_col_roles": {"zh": "用途", "en": "Role"},
    "llm_health_col_latest": {"zh": "最近调用", "en": "Latest call"},
    "llm_health_col_status": {"zh": "最新状态", "en": "Latest status"},
    "llm_health_col_calls": {"zh": "成功/调用", "en": "Succeeded / calls"},
    "llm_health_col_success_rate": {"zh": "成功率", "en": "Success rate"},
    "llm_health_col_last_error": {"zh": "最近失败信息（已脱敏）", "en": "Latest failure (redacted)"},
    "health_window_label": {"zh": "查看范围", "en": "View range"},
    "health_window_3": {"zh": "近 3 天", "en": "3 days"},
    "health_window_7": {"zh": "近 7 天", "en": "7 days"},
    "health_window_14": {"zh": "近 14 天", "en": "14 days"},
    "health_window_30": {"zh": "近 30 天", "en": "30 days"},
    "health_window_all": {"zh": "全部", "en": "All"},
    "pagination_page_size": {"zh": "每页显示", "en": "Rows per page"},
    "pagination_page_size_value": {"zh": "{size} 条", "en": "{size} rows"},
    "pagination_previous": {"zh": "← 上一页", "en": "← Previous"},
    "pagination_next": {"zh": "下一页", "en": "Next"},
    "pagination_info": {
        "zh": "第 {page} / {pages} 页 · {start}–{end} / 共 {total} 条",
        "en": "Page {page} of {pages} · {start}–{end} of {total}",
    },
    "an_diag_title": {"zh": "运行诊断", "en": "Run diagnostics"},
    "an_diag_runs_hint": {
        "zh": "显示所选时间范围内的每日研究与过去日报；旧历史维护任务请在“系统 → 历史维护”查看。",
        "en": "Shows daily-research and past-date runs in the selected range. View history-maintenance tasks in System → History Maintenance.",
    },
    "an_diag_runs_empty": {
        "zh": "尚无每日研究或过去日报运行记录。",
        "en": "No daily-research or past-date run is recorded yet.",
    },
    "an_diag_col_kind": {"zh": "任务", "en": "Task"},
    "an_diag_col_status": {"zh": "状态", "en": "Status"},
    "an_diag_col_started": {"zh": "开始时间", "en": "Started"},
    "an_diag_col_finished": {"zh": "完成时间", "en": "Finished"},
    "an_diag_col_papers": {"zh": "论文数", "en": "Papers"},
    "an_diag_col_issue": {"zh": "问题摘要", "en": "Issue summary"},
    "an_diag_status_completed": {"zh": "已完成", "en": "Completed"},
    "an_diag_status_failed": {"zh": "失败", "en": "Failed"},
    "an_diag_status_running": {"zh": "运行中", "en": "Running"},
    "an_diag_status_unknown": {"zh": "未知", "en": "Unknown"},
    "an_diag_recent_runs": {"zh": "近 10 次运行（完成/可用）", "en": "Last 10 runs (done/avail)"},
    "an_diag_recent_runs_help": {
        "zh": "分子为 completed 状态的运行数，分母为诊断窗口内可统计的运行数。",
        "en": "Completed runs over diagnosable runs in the recent window.",
    },
    "an_diag_failed_runs": {"zh": "近 10 次运行中有 {n} 次失败，请查看运行日志。", "en": "{n} of the last 10 runs failed; check the run logs."},
    "an_diag_latest_scan": {
        "zh": "最近一次扫描（{time}）：{ok}/{total} 个来源成功",
        "en": "Latest scan ({time}): {ok}/{total} sources succeeded",
    },
    "fav_state_like": {"zh": "已喜欢", "en": "Liked"},
    "fav_state_dislike": {"zh": "已不喜欢", "en": "Disliked"},
    "fav_hint": {
        "zh": "在报告里点 👍/👎 收藏论文；这里按时间浏览收藏、统计关键词，并可全量检索历史论文。",
        "en": "Mark papers with 👍/👎 in reports; browse them by time here, see keyword stats, and search the full history below.",
    },
    "fav_list_title": {"zh": "收藏的论文", "en": "Liked papers"},
    "fav_list_hint": {
        "zh": "按标记时间倒序；点击标题打开论文页面（arXiv 等）。",
        "en": "Newest marks first; click a title to open the paper page.",
    },
    "fav_no_likes": {
        "zh": "还没有收藏论文；在报告里点 👍 后会出现在这里。",
        "en": "No liked papers yet; tap 👍 in a report and they will appear here.",
    },
    "fav_keywords_title": {"zh": "收藏关键词统计", "en": "Liked keyword stats"},
    "fav_keywords_empty": {
        "zh": "收藏的论文还没有提取到关键词。",
        "en": "No extracted keywords among liked papers yet.",
    },
    "fav_likes": {"zh": "喜欢", "en": "Likes"},
    "fav_dislikes": {"zh": "不喜欢", "en": "Dislikes"},
    "fav_top_authors": {"zh": "收藏作者 Top", "en": "Top authors"},
    "fav_no_marks": {"zh": "还没有任何标记。", "en": "No marks yet."},
    # ── llm.py ───────────────────────────────────────────────────────────
    "cheap_llm_title": {
        "zh": "低成本 LLM (CHEAP_LLM)",
        "en": "Low-Cost LLM (CHEAP_LLM)",
    },
    "cheap_llm_hint": {
        "zh": "用于快速评分和关键词生成，选择速度快、成本低的模型。",
        "en": "Used for quick scoring and keyword generation. Choose a fast, cheap model.",
    },
    "provider_preset": {"zh": "服务商预设", "en": "Provider Preset"},
    "base_url": {"zh": "Base URL", "en": "Base URL"},
    "api_key": {"zh": "API Key", "en": "API Key"},
    "secret_configured_keep_blank": {
        "zh": "已保存；为保护密钥，留空会保留原值。",
        "en": "Saved; leave this blank to keep the existing secret.",
    },
    "model_name": {"zh": "模型名称", "en": "Model Name"},
    "temperature": {"zh": "Temperature", "en": "Temperature"},
    "test_cheap_btn": {
        "zh": "测试 CHEAP_LLM 连接",
        "en": "Test CHEAP_LLM Connection",
    },
    "test_smart_btn": {
        "zh": "测试 SMART_LLM 连接",
        "en": "Test SMART_LLM Connection",
    },
    "testing_connection": {"zh": "测试连接中...", "en": "Testing connection..."},
    "smart_llm_title": {
        "zh": "高性能 LLM (SMART_LLM)",
        "en": "High-Performance LLM (SMART_LLM)",
    },
    "smart_llm_hint": {
        "zh": "用于深度分析和内容理解，选择能力强的模型。",
        "en": "Used for deep analysis and content understanding. Choose a capable model.",
    },
    "third_party_keys_title": {
        "zh": "第三方 API 密钥",
        "en": "Third-Party API Keys",
    },
    "third_party_keys_hint": {
        "zh": "开启来源后才会调用对应服务；关闭时会隐藏其配置，已保存的密钥不会被清除。",
        "en": "A service is called only when enabled. Disabled service settings are hidden and saved keys are retained.",
    },
    "s2_api_key_label": {
        "zh": "Semantic Scholar API Key",
        "en": "Semantic Scholar API Key",
    },
    "openalex_api_key_label": {
        "zh": "OpenAlex API Key",
        "en": "OpenAlex API Key",
    },
    "openalex_section_title": {"zh": "OpenAlex", "en": "OpenAlex"},
    "openalex_section_hint": {
        "zh": "免费 API Key 可将每日 API 额度提高到匿名使用的 10 倍，并可查看用量。",
        "en": "A free API key gives 10× the anonymous daily API budget and usage visibility.",
    },
    "openalex_enabled_label": {
        "zh": "启用 OpenAlex 来源",
        "en": "Enable OpenAlex source",
    },
    "openalex_enabled_help": {
        "zh": "关闭后不会请求 OpenAlex。开启后，还需在「数据源 → 额外数据源」中选择期刊来源。",
        "en": "When off, OpenAlex is never queried. When on, select journal sources under Data Sources → Extra Sources as well.",
    },
    "test_openalex_btn": {"zh": "测试 OpenAlex 连接", "en": "Test OpenAlex Connection"},
    "testing_openalex": {"zh": "连接 OpenAlex 中...", "en": "Connecting to OpenAlex..."},
    "openalex_console_link": {
        "zh": "打开 OpenAlex API 控制台 ↗",
        "en": "Open OpenAlex API Dashboard ↗",
    },
    "semantic_scholar_section_title": {
        "zh": "Semantic Scholar",
        "en": "Semantic Scholar",
    },
    "semantic_scholar_section_hint": {
        "zh": "用于可选 TL;DR 增强。匿名额度由所有用户共享；API Key 初始限额为每秒 1 次，应用会自动按此节奏请求。",
        "en": "Used for optional TL;DR enrichment. Anonymous traffic uses a shared pool; API keys start at 1 request/second, which the app paces automatically.",
    },
    "semantic_scholar_enabled_label": {
        "zh": "启用 Semantic Scholar TL;DR 增强",
        "en": "Enable Semantic Scholar TL;DR enrichment",
    },
    "semantic_scholar_enabled_help": {
        "zh": "关闭后不会请求 Semantic Scholar，也不会把其 TL;DR 用于后续处理。",
        "en": "When off, Semantic Scholar is never queried and its TL;DR is not used for subsequent processing.",
    },
    "test_semantic_scholar_btn": {
        "zh": "测试 Semantic Scholar 连接",
        "en": "Test Semantic Scholar Connection",
    },
    "testing_semantic_scholar": {
        "zh": "连接 Semantic Scholar 中...",
        "en": "Connecting to Semantic Scholar...",
    },
    "semantic_scholar_console_link": {
        "zh": "打开 Semantic Scholar API 申请页 ↗",
        "en": "Open Semantic Scholar API Key Page ↗",
    },
    "mineru_api_key_label": {
        "zh": "MinerU API Key",
        "en": "MinerU API Key",
    },
    "mineru_section_title": {
        "zh": "MinerU PDF 解析 API",
        "en": "MinerU PDF Parsing API",
    },
    "mineru_section_hint": {
        "zh": "MinerU 提供高质量云端 PDF 解析，Token 每 3 个月过期。点击「测试」可查看颟度余量和过期时间。",
        "en": "MinerU provides high-quality cloud PDF parsing. Token expires every 3 months. Click Test to check quota and expiry.",
    },
    "mineru_key_help": {
        "zh": "登录 mineru.net 获取 API Token",
        "en": "Get your API token from mineru.net",
    },
    "test_mineru_btn": {"zh": "测试 MinerU 连接", "en": "Test MinerU Connection"},
    "mineru_console_link": {
        "zh": "打开 MinerU API 控制台 ↗",
        "en": "Open MinerU API Dashboard ↗",
    },
    "testing_mineru": {"zh": "连接 MinerU 中...", "en": "Connecting to MinerU..."},
    "mineru_expire_note": {
        "zh": "点击测试可查看 Token 过期日期和剩余颟度",
        "en": "Click Test to check token expiry and remaining quota",
    },
    # ── reports.py navigation ──
    "report_previous_report": {"zh": "← 上一份报告", "en": "← Previous Report"},
    "report_next_report": {"zh": "下一份报告", "en": "Next Report"},
    "report_show_non_arxiv": {"zh": "显示非 ArXiv 来源", "en": "Show non-ArXiv sources"},
    "report_no_prev": {"zh": "已是最早的报告", "en": "No earlier reports"},
    "report_no_next": {"zh": "已是最新的报告", "en": "No newer reports"},
    # ── run_manager.py ──
    "run_manager_title": {"zh": "每日推送", "en": "Daily Push"},
    "run_now_section_title": {"zh": "每日研究", "en": "Daily Research"},
    "run_now_btn": {"zh": "立即运行", "en": "Run Now"},
    "stop_all_btn": {"zh": "停止所有进程", "en": "Stop All Processes"},
    "run_log_title": {"zh": "运行日志", "en": "Run Logs"},
    "daily_research_settings_title": {"zh": "每日研究设置", "en": "Daily Research Settings"},
    "daily_max_papers_label": {
        "zh": "本次最多处理论文数",
        "en": "Maximum papers per run",
    },
    "daily_max_papers_help": {
        "zh": "单次运行最多处理的论文数，默认 200：首次部署会一次性抓到大量历史论文，上限确保不会一次处理过多，堆积由后续运行消化，消化完每天正常处理全部新论文；0 表示不限。抓取始终完整执行，剩余论文保存在 SQLite 中等待下次处理。",
        "en": "Maximum papers processed per run, default 200: a fresh deployment first collects a large backlog at once, so the cap prevents huge single runs while later runs drain the queue; once drained, each day's new papers are processed in full. 0 means unlimited. Scans always run complete; excess papers stay queued in SQLite.",
    },
    "daily_run_time_label": {"zh": "每日运行时间", "en": "Daily run time"},
    "daily_run_time_help": {
        "zh": "每天定时执行每日研究的时间（容器时区）。保存后点击侧边栏「重启主研究容器」即可生效。",
        "en": "Time of day (container timezone) the daily research runs. Use the “Restart Worker” sidebar button after saving.",
    },
    "markdown_report_label": {"zh": "Markdown 报告", "en": "Markdown Report"},
    "no_logs_found": {"zh": "暂未找到日志文件。", "en": "No log files found."},
    "pid_killed": {"zh": "已向进程 {pid} 发送停止信号", "en": "Sent stop signal to process {pid}"},
    "no_running_process": {
        "zh": "未检测到正在运行的进程。",
        "en": "No running processes detected.",
    },
    "process_started": {
        "zh": "进程已启动，日志将实时生成。",
        "en": "Process started. Logs will appear shortly.",
    },
    # run_manager 状态标签
    "rm_status_running": {"zh": "运行中", "en": "Running"},
    "rm_status_stopped": {"zh": "已停止（文件未清除）", "en": "Stopped (file not cleaned)"},
    "rm_no_pid": {"zh": "无 PID", "en": "No PID"},
    # run_manager 长任务进度反馈（阶段心跳 + 持久化队列计数）
    "rm_progress_phase_prepare": {"zh": "准备配置与关键词", "en": "Preparing config & keywords"},
    "rm_progress_phase_scan": {"zh": "抓取数据源", "en": "Scanning sources"},
    "rm_progress_phase_score": {"zh": "评分与翻译", "en": "Scoring & translating"},
    "rm_progress_phase_analyze": {"zh": "深度分析", "en": "Deep analysis"},
    "rm_progress_phase_report": {"zh": "生成报告", "en": "Writing reports"},
    "rm_progress_phase_legacy_import": {"zh": "导入旧历史", "en": "Importing legacy history"},
    "rm_progress_phase_legacy_history": {"zh": "读取旧 JSON 历史", "en": "Reading legacy JSON history"},
    "rm_progress_phase_legacy_keywords": {"zh": "整理报告关键词", "en": "Preparing report keywords"},
    "rm_progress_phase_legacy_reports": {"zh": "解析旧 HTML 报告", "en": "Parsing legacy HTML reports"},
    "rm_progress_phase_legacy_write": {"zh": "写入历史报告数据", "en": "Writing imported report data"},
    "rm_progress_phase_legacy_backlog": {"zh": "整理待补全数据", "en": "Preparing repair backlog"},
    "rm_progress_phase_legacy_scan": {"zh": "扫描旧历史时间段", "en": "Scanning legacy date range"},
    "rm_progress_phase_legacy_supplement": {"zh": "生成无报告历史补充", "en": "Building cardless-history supplements"},
    "rm_progress_phase_history_repair": {"zh": "补全历史数据", "en": "Repairing historical data"},
    "rm_progress_phase_history_omission_scan": {"zh": "扫描 SQLite 历史遗漏", "en": "Scanning SQLite historical omissions"},
    "rm_progress_phase_history_omission_week": {"zh": "按自然周生成补充报告", "en": "Building supplements by calendar week"},
    "rm_progress_caption": {
        "zh": "{phase} · 登记 {registered} · 已评分 {scored} · 深度分析 {analyzed} · 交付 {completed} · 失败 {failed} · 已运行 {elapsed}",
        "en": "{phase} · registered {registered} · scored {scored} · analyzed {analyzed} · delivered {completed} · failed {failed} · elapsed {elapsed}",
    },
    "rm_status_related_locks": {
        "zh": "同时持有的任务锁：{locks}。若为旧历史导入，表示它正在等待相关任务空闲或执行自动补充报告。",
        "en": "Other held task locks: {locks}. A legacy import may be waiting for related work to become idle or running its automatic supplement phase.",
    },
    "rm_process_running_label": {
        "zh": "面板触发的进程正在运行",
        "en": "Panel-triggered process is running",
    },
    "rm_no_panel_process": {
        "zh": "当前无面板触发的进程运行",
        "en": "No panel-triggered process running",
    },
    # run_manager Docker 模式
    "rm_docker_exec_hint": {
        "zh": "Docker 模式：通过 docker exec 在容器 {container} 中触发每日研究",
        "en": "Docker mode: triggers daily research via docker exec in container {container}",
    },
    "rm_docker_no_sock_warning": {
        "zh": (
            "⚠️ Docker 模式（无 Docker Socket）：无法直接启动任务。\n\n"
            "请在宿主机终端运行：\n"
            "`docker exec {container} python main.py --mode daily_research`"
        ),
        "en": (
            "⚠️ Docker mode (no Docker socket): cannot start tasks directly.\n\n"
            "Run on host terminal:\n"
            "`docker exec {container} python main.py --mode daily_research`"
        ),
    },
    "rm_docker_log_hint": {
        "zh": "（Docker 模式：确认 `logs/` 目录已通过卷挂载共享到此容器）",
        "en": "(Docker mode: ensure `logs/` is mounted into this container via a volume)",
    },
    # run_manager 日志选择器
    "rm_select_log_label": {"zh": "选择日志文件", "en": "Select log file"},
    "rm_select_log_help": {
        "zh": "按分类显示所有日志文件，括号内为最后修改时间",
        "en": "All log files grouped by type. Bracket shows last modified time.",
    },
    "rm_log_group_daily": {"zh": "每日研究日志", "en": "Daily Research"},
    "rm_log_group_trend": {"zh": "趋势分析日志", "en": "Trend Analysis"},
    "rm_log_group_other": {"zh": "其他日志", "en": "Other"},
    "rm_open_log_btn": {"zh": "打开", "en": "Open"},
    "rm_refresh_log_btn": {"zh": "刷新", "en": "Refresh"},
    "rm_close_log_btn": {"zh": "关闭", "en": "Close"},
    # ── trend_runner.py ──
    "trend_runner_title": {"zh": "趋势分析", "en": "Trend Analysis"},
    "trend_keywords_label": {"zh": "搜索关键词", "en": "Search Keywords"},
    "trend_keywords_help": {
        "zh": '多个关键词用空格分隔，引号包裹短语，如: quantum error correction "surface code"',
        "en": 'Multiple keywords separated by spaces. Quote phrases, e.g.: quantum error correction "surface code"',
    },
    "trend_date_from": {"zh": "起始日期", "en": "Date From"},
    "trend_date_to": {"zh": "截止日期", "en": "Date To"},
    "trend_categories_label": {
        "zh": "ArXiv 分类过滤（可选）",
        "en": "ArXiv Categories Filter (optional)",
    },
    "trend_categories_help": {
        "zh": "与搜索和数据源一致的分类下拉；不选则不过滤。",
        "en": "Same category dropdown as Search & Data Sources; leave empty for no filter.",
    },
    "trend_run_btn": {"zh": "开始趋势分析", "en": "Start Trend Analysis"},
    "trend_config_title": {"zh": "趋势分析配置", "en": "Trend Analysis Configuration"},
    "trend_sort_label": {"zh": "时间排序", "en": "Time Sort Order"},
    "trend_generate_tldr_label": {"zh": "生成 TLDR", "en": "Generate TLDR"},
    "trend_tldr_batch_label": {"zh": "TLDR 批次并发数", "en": "TLDR Batch Size"},
    "trend_skills_label": {"zh": "分析技能", "en": "Analysis skills"},
    "trend_output_formats_label": {"zh": "输出格式", "en": "Output Formats"},
    "trend_output_md_label": {"zh": "Markdown 报告", "en": "Markdown Report"},
    "trend_output_html_label": {"zh": "HTML 报告", "en": "HTML Report"},
    "trend_keywords_placeholder": {
        "zh": "quantum error correction · surface code",
        "en": "quantum error correction · surface code",
    },
    "trend_prompt_label": {"zh": "深度分析提示词", "en": "Deep-analysis prompt"},
    "trend_prompt_help": {
        "zh": "自定义「综合分析」的分析要求；留空使用内置综合分析指令。运行时立即生效，也可保存为模板复用。",
        "en": "Custom instructions for the comprehensive analysis; leave blank to use the built-in one. Applies immediately on run and can be saved as a template.",
    },
    "trend_prompt_placeholder": {
        "zh": "例如：请重点分析……并按……结构输出（留空使用内置指令）",
        "en": "e.g. Focus on ... and structure the output as ... (blank = built-in)",
    },
    "trend_prompt_template_label": {"zh": "提示词模板", "en": "Prompt template"},
    "trend_prompt_template_help": {
        "zh": "选择已保存的模板并应用到提示词框。",
        "en": "Pick a saved template to load it into the prompt box.",
    },
    "trend_prompt_template_none": {"zh": "默认（不自定义）", "en": "Default (no customization)"},
    "trend_prompt_add_title": {"zh": "新增自定义提示词", "en": "Add custom prompt"},
    "trend_prompt_add_btn": {"zh": "添加", "en": "Add"},
    "trend_prompt_template_delete": {"zh": "删除模板", "en": "Delete"},
    "trend_prompt_template_deleted": {"zh": "模板已删除", "en": "Template deleted"},
    "trend_prompt_template_save": {"zh": "保存为模板", "en": "Save template"},
    "trend_prompt_template_saved": {"zh": "模板已保存", "en": "Template saved"},
    "trend_prompt_template_name_label": {"zh": "模板名称", "en": "Template name"},
    "trend_prompt_template_name_placeholder": {"zh": "给当前提示词起个名字", "en": "Name this prompt"},
    "trend_prompt_template_name_required": {"zh": "请先填写模板名称。", "en": "Enter a template name first."},
    "trend_prompt_template_text_required": {"zh": "提示词为空，无需保存模板。", "en": "The prompt is empty; nothing to save."},
    # ── search.py ────────────────────────────────────────────────────────
    "arxiv_source_enabled": {"zh": "启用 arXiv 来源", "en": "Enable arXiv source"},
    "sh_hint": {
        "zh": "汇总所有真实任务（含历史维护）的数据源请求与补充查询；查看不会发起额外请求。",
        "en": "Summarizes source requests and enrichment from all real tasks, including history maintenance; viewing makes no extra request.",
    },
    "extra_sources_title": {"zh": "额外数据源", "en": "Extra Data Sources"},
    "extra_sources_enabled": {"zh": "启用额外数据源", "en": "Enable extra data sources"},
    "extra_sources_help": {"zh": "关闭时保留已配置的来源但不抓取。", "en": "When off, configured sources are kept but not scanned."},
    "extra_sources_builtin_label": {"zh": "内置来源（多选）", "en": "Built-in sources (multi-select)"},
    "extra_sources_custom_title": {"zh": "自定义来源", "en": "Custom sources"},
    "extra_sources_add_title": {"zh": "➕ 新增自定义来源", "en": "➕ Add a custom source"},
    "extra_sources_add_code": {"zh": "来源代码（小写字母/数字/下划线）", "en": "Source code (lowercase/digits/underscore)"},
    "extra_sources_add_display": {"zh": "显示名称", "en": "Display name"},
    "extra_sources_add_full": {"zh": "期刊全名", "en": "Full journal name"},
    "extra_sources_add_issn": {"zh": "ISSN（逗号分隔）", "en": "ISSNs (comma separated)"},
    "extra_sources_add_btn": {"zh": "添加来源", "en": "Add source"},
    "extra_sources_added": {"zh": "已添加自定义来源。", "en": "Custom source added."},
    "extra_sources_removed": {"zh": "已移除自定义来源。", "en": "Custom source removed."},
    "extra_sources_invalid": {"zh": "来源定义无效", "en": "Invalid source definitions"},
    "reports_by_source_toggle": {
        "zh": "按数据源分类整理报告",
        "en": "Organize reports by source",
    },
    "reports_by_source_help": {
        "zh": "为每个数据源创建独立报告目录",
        "en": "Create separate report directories for each data source",
    },
    "arxiv_fetch_timeout_label": {
        "zh": "ArXiv 抓取超时（秒）",
        "en": "ArXiv fetch timeout (seconds)",
    },
    "arxiv_fetch_timeout_help": {
        "zh": "单次 ArXiv 抓取硬超时，超时后自动重试，避免任务长时间卡住",
        "en": "Hard timeout for one ArXiv fetch. Retries on timeout to avoid stuck runs.",
    },
    "arxiv_announcement_lookback_grace_label": {
        "zh": "ArXiv 延迟公告回看（天）",
        "en": "ArXiv delayed-announcement lookback (days)",
    },
    "arxiv_announcement_lookback_grace_help": {
        "zh": "额外回看可能因周末公告或 API 索引延迟而晚出现的论文。已交付的同一版本会自动去重，不会重复推送。",
        "en": "Rescan this many extra days for papers delayed by announcements or API indexing. Delivered exact versions are deduplicated.",
    },
    "huggingface_papers_source_notice": {
        "zh": "Hugging Face Papers 是可选的精选补充流，不是 arXiv 全量来源。启用后会完整分页；与本次 arXiv 扫描或已交付 arXiv 镜像重复的条目会自动跳过。",
        "en": "Hugging Face Papers is an optional curated supplementary feed, not a complete arXiv source. When enabled, all pages are fetched; mirrors already found or delivered through arXiv are skipped.",
    },
    "huggingface_papers_availability_lag_label": {
        "zh": "HF 日榜可用性滞后（天）",
        "en": "HF feed availability lag (days)",
    },
    "huggingface_papers_availability_lag_help": {
        "zh": "避免将尚未形成的当天日榜误判为“没有论文”；默认读取两天前及更早的日榜。",
        "en": "Avoid treating a not-yet-final daily feed as empty; by default, fetches feeds from two days ago and earlier.",
    },
    "huggingface_papers_lookback_grace_label": {
        "zh": "HF 日榜额外回看（天）",
        "en": "HF feed extra lookback (days)",
    },
    "huggingface_papers_lookback_grace_help": {
        "zh": "对已可用日榜额外重扫近期日期，以抵御展示或索引延迟；精确交付账本会去重。",
        "en": "Rescan additional already-available feeds for display or indexing delays; the exact delivery ledger prevents duplicates.",
    },
    "huggingface_papers_request_timeout_label": {
        "zh": "HF 单页请求超时（秒）",
        "en": "HF per-page request timeout (seconds)",
    },
    "huggingface_papers_request_interval_label": {
        "zh": "HF 请求间隔（秒）",
        "en": "HF request interval (seconds)",
    },
    "huggingface_papers_request_interval_help": {
        "zh": "只限制请求速率，不限制结果数量或处理范围。",
        "en": "Limits request rate only; it never caps result count or processing scope.",
    },
    "arxiv_domains_hint": {
        "zh": "内置 arXiv 全部一级分类（按字母排序），下拉多选即可。",
        "en": "All primary arXiv categories are built in (alphabetical); pick from the dropdown.",
    },
    "select_arxiv_cats": {
        "zh": "选择 ArXiv 分类",
        "en": "Select ArXiv categories",
    },
    # ── keywords.py ──────────────────────────────────────────────────────
    "primary_keywords_title": {"zh": "主要关键词", "en": "Primary Keywords"},
    "primary_keywords_hint": {
        "zh": "用于论文相关性评分的关键词，权重越高越重要。",
        "en": "Keywords used for paper relevance scoring. Higher weight = more importance.",
    },
    "keywords_textarea_label": {
        "zh": "主要关键词（每行一个）",
        "en": "Primary Keywords (one per line)",
    },
    "keywords_textarea_help": {
        "zh": "每行输入一个关键词，用于匹配论文标题和摘要。",
        "en": "Enter one keyword per line. These are matched against paper titles and abstracts.",
    },
    "keyword_weight_slider": {
        "zh": "主要关键词权重",
        "en": "Primary Keyword Weight",
    },
    "ref_extract_title": {
        "zh": "参考文献 PDF 关键词提取",
        "en": "Reference PDF Extraction",
    },
    "ref_extract_hint": {
        "zh": "自动从 data/reference_pdfs/ 中的参考 PDF 提取关键词。",
        "en": "Automatically extract keywords from reference PDFs in data/reference_pdfs/",
    },
    "enable_ref_extract": {
        "zh": "启用参考文献关键词提取",
        "en": "Enable reference keyword extraction",
    },
    "max_extracted_kws": {
        "zh": "最大提取关键词数",
        "en": "Max extracted keywords",
    },
    "similarity_threshold_label": {
        "zh": "相似度阈值",
        "en": "Similarity threshold",
    },
    "similarity_threshold_help": {
        "zh": "相似度高于此阈值的关键词将被去重",
        "en": "Keywords above this similarity are de-duplicated",
    },
    "weight_distribution": {
        "zh": "**权重分布**",
        "en": "**Weight Distribution**",
    },
    "high_importance": {"zh": "🔥 高重要性", "en": "🔥 High Importance"},
    "medium_importance": {"zh": "⚖️ 中重要性", "en": "⚖️ Medium Importance"},
    "low_importance": {"zh": "🪶 低重要性", "en": "🪶 Low Importance"},
    "weight_label": {"zh": "权重", "en": "Weight"},
    "count_label": {"zh": "数量", "en": "Count"},
    "kw_extracted_title": {"zh": "已提取的关键词", "en": "Extracted keywords"},
    "kw_extracted_empty": {
        "zh": "还没有从参考文献 PDF 提取到关键词；运行一次每日研究后会出现在这里。",
        "en": "No keywords extracted from reference PDFs yet; they appear here after a daily run.",
    },
    "kw_extracted_count": {"zh": "共 {total} 个（按权重排序）", "en": "{total} total (by weight)"},
    "research_context_title": {"zh": "研究背景", "en": "Research Context"},
    "research_context_hint": {
        "zh": "描述你的研究领域，帮助 LLM 更好地理解相关性。",
        "en": "Describe your research area to help the LLM better understand relevance.",
    },
    "research_context_label": {"zh": "研究背景", "en": "Research Context"},
    "research_context_placeholder": {
        "zh": "例如：我研究量子纠错和拓扑量子计算...",
        "en": "e.g., I study quantum error correction and topological quantum computing...",
    },
    # ── scoring.py ───────────────────────────────────────────────────────
    "scoring_title": {"zh": "评价策略", "en": "Evaluation Policy"},
    "scoring_hint": {
        "zh": "选择论文如何获得资格，以及通过后如何排序。新配置建议使用核心相关性 V2。",
        "en": "Choose how papers qualify and how qualified papers rank. Core relevance V2 is recommended for new configurations.",
    },
    "score_strategy_label": {"zh": "评分策略", "en": "Scoring Strategy"},
    "score_strategy_help": {
        "zh": "界面显示本地化名称；保存时仍写入稳定的策略 ID，不会因切换语言改变行为。",
        "en": "The selector is localized, while saving keeps the stable strategy ID; changing language never changes behavior.",
    },
    "score_strategy_core_relevance_v2_label": {
        "zh": "核心相关性 V2（推荐）",
        "en": "Core relevance V2 (Recommended)",
    },
    "score_strategy_legacy_weighted_keyword_v1_label": {
        "zh": "加权关键词 V1（兼容）",
        "en": "Weighted keywords V1 (Compatibility)",
    },
    "score_strategy_learned_preference_v1_label": {
        "zh": "偏好学习 V1（个性化）",
        "en": "Learned preference V1 (Personalized)",
    },
    "score_strategy_core_relevance_v2_description": {
        "zh": "先由模型为每个关键词给出内容相关度。资格只看主关键词：按主关键词权重计算平均相关度，并且至少一个主关键词达到“强匹配”门槛；两项都满足才通过。通过后，参考关键词和收藏作者只用于排序，不能让无关论文获得资格。",
        "en": "The model scores content relevance for each keyword. Qualification uses primary keywords only: their weighted-average relevance must pass, and at least one primary keyword must reach the strong-match threshold. Both are required. After qualification, reference terms and preferred authors only affect ranking; they cannot qualify an unrelated paper.",
    },
    "score_strategy_legacy_weighted_keyword_v1_description": {
        "zh": "将主关键词和参考关键词的得分按权重累加，再叠加专家作者加分；总分达到“基础分 + 权重系数 × 全部关键词总权重”即通过。参考词和作者加分同时影响资格与排序，适合复现旧报告或临时回退，但可能放大非核心信号。",
        "en": "Scores from primary and reference keywords are summed by weight, then expert-author bonuses are added. A paper passes when the total reaches “base score + weight coefficient × total keyword weight.” Reference terms and author bonuses affect both qualification and ranking. Use it to reproduce old reports or temporarily roll back; non-core signals can carry more influence.",
    },
    "score_strategy_learned_preference_v1_description": {
        "zh": "以加权关键词 V1 为基础，再加入从喜欢/不喜欢和历史通过记录学习到的关键词、作者偏好。每个学习项先限幅再衰减，且已直接配置的关键词不会重复计算；但学习项仍会改变总分，因此也可能改变资格。适合个人化筛选，不适合严格复现基准结果。",
        "en": "Builds on weighted keywords V1 and adds keyword/author preferences learned from likes, dislikes, and past passing papers. Each learned term is capped then dampened, and directly configured keywords are not counted twice. The learned adjustment still changes the total and can therefore change qualification. Use it for personal curation, not strict benchmark reproduction.",
    },
    "core_relevance_info": {
        "zh": "V2 资格要求：主关键词的加权平均相关度达到门槛，且至少一个主关键词强匹配。参考关键词和专家作者仅用于合格论文排序，不能让无关论文通过。",
        "en": "V2 qualification requires a passing weighted average across primary keywords and one strong primary match. Reference terms and expert authors only rank qualified papers; they cannot pass an unrelated paper.",
    },
    "core_relevance_threshold_label": {"zh": "核心相关性门槛", "en": "Core Relevance Threshold"},
    "core_keyword_min_score_label": {"zh": "核心词强匹配门槛", "en": "Strong Core Match Threshold"},
    "reference_ranking_weight_label": {"zh": "参考词排序系数", "en": "Reference Ranking Weight"},
    "reference_ranking_weight_help": {
        "zh": "仅影响已合格论文的排序，不参与是否推荐。",
        "en": "Only ranks already qualified papers; it never affects recommendation eligibility.",
    },
    "core_relevance_no_primary_warning": {
        "zh": "尚未配置主要关键词，且参考文献关键词提取未启用。运行无法开始；请添加主要关键词，或启用参考文献关键词提取并提供参考 PDF。",
        "en": "No primary keywords are configured and reference keyword extraction is off. The run cannot start; add primary keywords, or enable extraction and provide reference PDFs.",
    },
    "core_relevance_reference_only_info": {
        "zh": "尚未配置主要关键词。此次运行会先从参考文献 PDF 提取可用关键词；提取到的关键词将临时作为核心集合。若没有可用 PDF 或提取结果为空，运行会给出明确提示。",
        "en": "No primary keywords are configured. This run will first extract usable terms from reference PDFs and use them as a temporary core set. It will clearly report if no readable PDF or usable term is available.",
    },
    "legacy_strategy_warning": {
        "zh": "兼容模式：作者加分和参考关键词仍会影响是否通过。只建议用于与既有历史结果对比或暂时回退。",
        "en": "Compatibility mode: author bonuses and reference keywords still affect qualification. Use only for historical comparison or a temporary rollback.",
    },
    "base_score_label": {"zh": "基础分", "en": "Base Score"},
    "weight_coeff_label": {"zh": "权重系数", "en": "Weight Coefficient"},
    "max_score_per_kw_label": {
        "zh": "每个关键词最高得分",
        "en": "Max Score Per Keyword",
    },
    "author_bonus_title": {"zh": "作者加分", "en": "Author Bonus"},
    "author_bonus_hint": {
        "zh": "给指定作者的论文额外加分。",
        "en": "Give extra points to papers by specific authors.",
    },
    "enable_author_bonus": {
        "zh": "启用作者加分",
        "en": "Enable author bonus",
    },
    "expert_authors_label": {
        "zh": "专家作者（每行一个）",
        "en": "Expert Authors (one per line)",
    },
    "expert_authors_help": {
        "zh": "包含这些作者的论文将获得额外分数",
        "en": "Papers with these authors receive bonus points",
    },
    "bonus_points_label": {"zh": "加分分值", "en": "Bonus Points"},
    "report_settings_title": {"zh": "报告设置", "en": "Report Settings"},
    "include_all_in_report": {
        "zh": "报告中包含所有论文（不仅是通过的）",
        "en": "Include all papers in report (not just passing)",
    },
    "include_all_help": {
        "zh": "关闭后，报告中只包含高于通过分数的论文",
        "en": "If disabled, only papers above the passing score are included",
    },
    # ── notifications.py ─────────────────────────────────────────────────
    "notif_settings_title": {"zh": "通知设置", "en": "Notification Settings"},
    "notif_settings_hint": {
        "zh": "运行完成时发送通知，在下方配置各通知渠道。",
        "en": "Send notifications when runs complete. Configure channels below.",
    },
    "enable_notifications": {
        "zh": "启用通知",
        "en": "Enable notifications",
    },
    "notify_success": {"zh": "成功时通知", "en": "Notify on success"},
    "notify_failure": {"zh": "失败时通知", "en": "Notify on failure"},
    "top_n_label": {"zh": "通知中展示 Top-N 篇论文", "en": "Top-N papers in notification"},
    "attach_reports": {
        "zh": "邮件附带报告文件",
        "en": "Attach report files to email",
    },
    "email_expander": {"zh": "邮件 (SMTP)", "en": "Email (SMTP)"},
    "enable_email": {"zh": "启用邮件", "en": "Enable Email"},
    "smtp_host_label": {"zh": "SMTP 服务器", "en": "SMTP Host"},
    "smtp_port_label": {"zh": "SMTP 端口", "en": "SMTP Port"},
    "use_tls_label": {"zh": "使用 TLS", "en": "Use TLS"},
    "smtp_user_label": {"zh": "SMTP 用户名", "en": "SMTP User"},
    "smtp_password_label": {"zh": "SMTP 密码", "en": "SMTP Password"},
    "from_address_label": {"zh": "发件人地址", "en": "From Address"},
    "to_addresses_label": {
        "zh": "收件人地址（逗号分隔）",
        "en": "To Addresses (comma-separated)",
    },
    "test_email_btn": {"zh": "测试邮件连接", "en": "Test Email Connection"},
    "testing_smtp": {"zh": "测试 SMTP 中...", "en": "Testing SMTP..."},
    "wechat_expander": {"zh": "企业微信", "en": "WeChat Work"},
    "enable_wechat": {"zh": "启用企业微信", "en": "Enable WeChat Work"},
    "webhook_url_label": {"zh": "Webhook URL", "en": "Webhook URL"},
    "dingtalk_expander": {"zh": "钉钉", "en": "DingTalk"},
    "enable_dingtalk": {"zh": "启用钉钉", "en": "Enable DingTalk"},
    "secret_optional_label": {"zh": "签名密钥（可选）", "en": "Secret (optional)"},
    "telegram_expander": {"zh": "Telegram", "en": "Telegram"},
    "enable_telegram": {"zh": "启用 Telegram", "en": "Enable Telegram"},
    "bot_token_label": {"zh": "Bot Token", "en": "Bot Token"},
    "chat_id_label": {"zh": "Chat ID", "en": "Chat ID"},
    "slack_expander": {"zh": "Slack", "en": "Slack"},
    "enable_slack": {"zh": "启用 Slack", "en": "Enable Slack"},
    "generic_webhook_expander": {
        "zh": "通用 Webhook",
        "en": "Generic Webhook",
    },
    "enable_generic_webhook": {
        "zh": "启用通用 Webhook",
        "en": "Enable Generic Webhook",
    },
    # ── advanced.py ──────────────────────────────────────────────────────
    "pdf_parser_title": {"zh": "PDF 解析器", "en": "PDF Parser"},
    "pdf_parser_hint": {
        "zh": "选择解析研究论文 PDF 的方式。",
        "en": "Choose how to parse research paper PDFs.",
    },
    "parser_mode_label": {"zh": "解析器模式", "en": "Parser Mode"},
    "parser_mode_help": {
        "zh": "mineru：云端 API（质量更高）| pymupdf：本地（无需网络）",
        "en": "mineru: cloud API (higher quality) | pymupdf: local (no network)",
    },
    "mineru_version_label": {
        "zh": "MinerU 模型版本",
        "en": "MinerU Model Version",
    },
    "mineru_version_help": {
        "zh": "pipeline：速度快 | vlm：更精准（消耗更多配额）",
        "en": "pipeline: fast | vlm: more accurate (uses more quota)",
    },
    "pdf_download_max_mb_label": {
        "zh": "PDF 下载大小上限（MB）",
        "en": "PDF Download Size Limit (MB)",
    },
    "pdf_download_max_mb_help": {
        "zh": "深度分析下载的单个 PDF 上限；超限或非 PDF 响应会保留论文供后续重试。",
        "en": "Per-PDF deep-analysis limit; oversized or non-PDF responses remain retryable.",
    },
    "concurrency_title": {"zh": "并发设置", "en": "Concurrency"},
    "concurrency_hint": {
        "zh": "LLM 评分的并行处理，注意 API 速率限制。",
        "en": "Parallel processing for LLM scoring. Watch for API rate limits.",
    },
    "enable_concurrency": {
        "zh": "启用并发处理",
        "en": "Enable concurrent processing",
    },
    "worker_threads_label": {"zh": "工作线程数", "en": "Worker threads"},
    "worker_threads_help": {
        "zh": "推荐：3-5，过高可能触发速率限制。",
        "en": "Recommended: 3-5. Higher values may trigger rate limits.",
    },
    "llm_pool_title": {"zh": "LLM 请求池", "en": "LLM Request Pool"},
    "llm_pool_hint": {
        "zh": "全局限制 LLM 请求速率，避免并发任务触发 API 限流。",
        "en": "Globally limit LLM request rate to avoid API throttling.",
    },
    "enable_llm_pool": {"zh": "启用 LLM 请求池", "en": "Enable LLM request pool"},
    "llm_rpm_label": {"zh": "每分钟请求数", "en": "Requests per minute"},
    "llm_slow_wait_label": {"zh": "慢等待日志阈值（秒）", "en": "Slow-wait log threshold (seconds)"},
    "daily_persistence_title": {
        "zh": "每日研究持久化",
        "en": "Daily Research Persistence",
    },
    "daily_persistence_hint": {
        "zh": "保存论文级评分与分析进度，用于断点续跑和失败恢复。",
        "en": "Save paper-level scoring and analysis progress for resume and recovery.",
    },
    "enable_daily_persistence": {
        "zh": "启用论文级持久化",
        "en": "Enable paper-level persistence",
    },
    "daily_db_path_label": {"zh": "持久化数据库路径", "en": "Persistence database path"},
    "daily_deep_analysis_label": {"zh": "启用每日深度分析", "en": "Enable daily deep analysis"},
    "advanced_reports_title": {"zh": "功能开关", "en": "Feature Toggles"},
    "html_reports_label": {"zh": "HTML 报告", "en": "HTML reports"},
    "token_tracking_label": {"zh": "Token 用量追踪", "en": "Token tracking"},
    "auto_update_label": {
        "zh": "检查新版本并通知",
        "en": "Check for updates & notify",
    },
    "auto_update_help": {
        "zh": "只检查 GitHub Release，不会自动拉取代码、重建镜像或重启容器。发现比当前版本更新的发布版时，经已启用的通知渠道提醒；若所有渠道未送达，后续检查会重试。",
        "en": "Checks GitHub Releases only; it never pulls code, rebuilds images, or restarts containers. A newer release is sent through enabled notification channels, and failed delivery is retried by a later check.",
    },
    "kw_tracker_title": {
        "zh": "关键词趋势追踪",
        "en": "Keyword Trend Tracking",
    },
    "enable_kw_tracker": {
        "zh": "启用关键词追踪",
        "en": "Enable keyword tracking",
    },
    "ai_normalization_label": {
        "zh": "AI 归一化",
        "en": "AI normalization",
    },
    "normalization_batch_label": {
        "zh": "归一化批次大小",
        "en": "Normalization batch size",
    },
    "trend_view_days_label": {
        "zh": "默认趋势视图天数",
        "en": "Default trend view (days)",
    },
    "bar_chart_top_n_label": {
        "zh": "柱状图 Top-N",
        "en": "Bar chart top-N",
    },
    "trend_chart_top_n_label": {
        "zh": "趋势图 Top-N",
        "en": "Trend chart top-N",
    },
    "enable_trend_reports_label": {
        "zh": "启用趋势报告",
        "en": "Enable trend reports",
    },
    "report_frequency_label": {
        "zh": "报告频率",
        "en": "Report frequency",
    },
    "retry_title": {"zh": "重试与日志", "en": "Retry & Logging"},
    "max_retries_label": {"zh": "最大重试次数", "en": "Max retry attempts"},
    "min_wait_label": {"zh": "最短等待（秒）", "en": "Min wait (seconds)"},
    "max_wait_label": {"zh": "最长等待（秒）", "en": "Max wait (seconds)"},
    "run_lock_max_age_label": {
        "zh": "运行锁超龄告警阈值（小时）",
        "en": "Run-lock long-run warning threshold (hours)",
    },
    "run_lock_max_age_help": {
        "zh": "同一任务超过该时长时，后续同类任务会告警并跳过；不会按 PID 自动终止进程。",
        "en": (
            "If a task exceeds this duration, a later matching run warns and "
            "skips it; no process is terminated by PID automatically."
        ),
    },
    "log_rotation_label": {"zh": "日志轮转方式", "en": "Log rotation"},
    "log_retention_label": {"zh": "日志保留天数", "en": "Log retention (days)"},
    "trend_research_title": {
        "zh": "趋势研究模式",
        "en": "Trend Research Mode",
    },
    "trend_date_range_label": {
        "zh": "默认日期范围（天）",
        "en": "Default date range (days)",
    },
    "trend_sort_order_label": {"zh": "排序方式", "en": "Sort order"},
    "trend_max_results_label": {"zh": "最大结果数", "en": "Max results"},
    "trend_report_position_label": {
        "zh": "报告位置",
        "en": "Report position",
    },
    "generate_tldr_label": {"zh": "生成 TLDR", "en": "Generate TLDR"},
    "tldr_batch_size_label": {
        "zh": "TLDR 批次大小",
        "en": "TLDR batch size",
    },
    "enabled_skills_label": {
        "zh": "**启用的分析技能**",
        "en": "**Enabled Analysis Skills**",
    },
    # Skill names
    "skill_comprehensive_analysis": {
        "zh": "综合趋势分析",
        "en": "Comprehensive Trend Analysis",
    },
    # ── reports.py ────────────────────────────────────────────────────────
    "reports_title": {"zh": "报告查看", "en": "Report Viewer"},
    "reports_hint": {
        "zh": "浏览并在线预览所有已生成的 HTML 报告，包括每日研究、趋势分析、关键词趋势和补充报告。",
        "en": (
            "Browse and preview all generated HTML reports: daily research, trend "
            "analysis, keyword trend, and supplement reports."
        ),
    },
    "reports_refresh": {"zh": "刷新文件列表", "en": "Refresh File List"},
    "reports_empty": {
        "zh": "当前报告目录下暂无 HTML 报告，请先运行一次研究任务。",
        "en": "No HTML reports found in the current reports directory. Run a research task first.",
    },
    "reports_empty_type": {"zh": "暂无报告", "en": "No reports"},
    "reports_count_unit": {"zh": "份", "en": "reports"},
    "reports_preview_btn": {"zh": "▶ 预览", "en": "▶ Preview"},
    "reports_dir_label": {"zh": "报告目录", "en": "Reports directory"},
    "rtype_daily": {"zh": "每日研究", "en": "Daily Research"},
    "rtype_trend": {"zh": "趋势分析", "en": "Trend Analysis"},
    "rtype_keyword_trend": {"zh": "关键词趋势", "en": "Keyword Trend"},
    "rtype_supplement": {"zh": "补充报告", "en": "Supplement Report"},
    "rtype_other": {"zh": "其他报告", "en": "Other Reports"},
    "reports_meta_expander": {"zh": "运行参数", "en": "Run Parameters"},
    "meta_keyword": {"zh": "关键词", "en": "Keyword"},
    "meta_date_range": {"zh": "日期范围", "en": "Date Range"},
    "meta_papers": {"zh": "论文数量", "en": "Paper Count"},
    "reports_mtime": {"zh": "生成时间", "en": "Generated"},
    "reports_height": {"zh": "预览高度", "en": "Preview Height"},
    "reports_load_error": {"zh": "报告加载失败", "en": "Failed to load report"},
    # ── trend_runner.py 新增 i18n ──
    "tr_section_params": {"zh": "分析参数", "en": "Analysis Parameters"},
    "tr_section_run_control": {"zh": "运行控制", "en": "Run Control"},
    "tr_default_date_range_days_label": {
        "zh": "默认时间范围（天）",
        "en": "Default date range (days)",
    },
    "tr_default_date_range_days_help": {
        "zh": "保存后作为新建分析的默认时间范围",
        "en": "Saved as the default date range for new analyses",
    },
    "tr_stop_btn_label": {"zh": "⏹ 停止趋势分析", "en": "⏹ Stop Trend Analysis"},
    "tr_locks_found": {
        "zh": "当前有 {n} 个趋势分析任务锁文件存在（可能正在运行或异常退出）。",
        "en": "{n} trend analysis lock file(s) found (may be running or crashed).",
    },
    "tr_stop_signal_sent": {
        "zh": "已向趋势分析进程 PID={pid} 发送停止信号 ({name})",
        "en": "Sent stop signal to trend analysis process PID={pid} ({name})",
    },
    "tr_stop_failed": {"zh": "停止 PID={pid} 失败: {err}", "en": "Failed to stop PID={pid}: {err}"},
    "tr_no_running_trend": {
        "zh": "未检测到正在运行的趋势分析进程。",
        "en": "No running trend analysis processes detected.",
    },
    "tr_err_no_keywords": {"zh": "请输入搜索关键词。", "en": "Please enter search keywords."},
    "tr_err_date_range": {
        "zh": "起始日期不能晚于截止日期。",
        "en": "Start date cannot be later than end date.",
    },
    "tr_started": {
        "zh": "趋势分析已启动！PID={pid}，请在「报告查看」Tab 中查看结果。",
        "en": "Trend analysis started! PID={pid}. Check the Reports tab for results.",
    },
    "tr_start_failed": {"zh": "启动失败: {err}", "en": "Failed to start: {err}"},
    # skill labels (also fix time_evolution and key_researchers missing earlier)
    # run_manager 触发文件机制新 key
    "rm_trigger_pending": {
        "zh": "已发送运行请求，等待主研究容器响应（最多 10 秒）...",
        "en": "Run request sent, waiting for researcher container to respond (up to 10s)...",
    },
    "rm_trigger_pending_short": {
        "zh": "等待主容器响应中...",
        "en": "Waiting for main container...",
    },
    "rm_trigger_sent": {
        "zh": "✅ 已发送运行请求！主研究容器将在 5-10 秒内启动任务，日志将在「运行日志」区实时更新。",
        "en": "✅ Run request sent! The researcher container will start the task within 5-10 seconds. Check the Run Logs section.",
    },
    "rm_trigger_failed": {
        "zh": "❌ 写入触发文件失败",
        "en": "❌ Failed to write trigger file",
    },
    "rm_launch_failed": {
        "zh": "❌ 启动失败，请查看运行日志",
        "en": "❌ Could not start the run; check the run log",
    },
    "rm_already_running_warn": {
        "zh": "检测到已有一个进程在运行（PID={pid}），请先停止后再启动。",
        "en": "A process is already running (PID={pid}). Please stop it before starting a new one.",
    },
    # ── run_manager v2 新增 key ──
    "rm_trigger_stale": {
        "zh": "触发文件已存在 {n} 秒仍未被主容器消费，可能主研究容器未运行。请检查后清除。",
        "en": "Trigger file has been pending for {n}s without being consumed. The researcher container may not be running. Please check and clear it.",
    },
    "rm_clear_trigger_btn": {"zh": "🗑 清除触发文件", "en": "🗑 Clear Trigger File"},
    "rm_trigger_sent_short": {
        "zh": "已发送运行请求！主容器将在 5-10s 内启动",
        "en": "Run request sent! Container will start within 5-10s",
    },
    # ── 过去时间段每日报告 ──
    "rm_status_panel_title": {"zh": "状态面板", "en": "Status Panel"},
    "rm_backfill_section_title": {"zh": "过去日报", "en": "Past Daily Reports"},
    "rm_backfill_date_from_label": {"zh": "起始日期", "en": "Start date"},
    "rm_backfill_date_to_label": {"zh": "结束日期", "en": "End date"},
    "rm_backfill_help": {
        "zh": "所选日期会进入持久化队列，按天从早到晚逐日运行；每一天只处理当天提交且尚未推送过的论文，报告时间戳使用该日期 + 实际运行时刻，会消耗 LLM 额度。",
        "en": "The selected dates enter a durable queue and run one day at a time, oldest first. Each day processes its undelivered submissions and stamps the report with that date plus the actual run time; LLM quota is consumed.",
    },
    "rm_backfill_btn": {"zh": "开始运行", "en": "Start Run"},
    "rm_backfill_sent": {
        "zh": "已加入过去日报队列，将在空闲时按日期顺序逐日运行。",
        "en": "Added to the past-report queue; it will run day by day when idle.",
    },
    "rm_backfill_invalid_range": {
        "zh": "结束日期不能早于起始日期。",
        "en": "The end date cannot be earlier than the start date.",
    },
    "rm_backfill_queue_line": {
        "zh": "队列：待处理 {pending} · 运行中 {running} · 已完成 {completed} · 失败 {failed}{active}",
        "en": "Queue: pending {pending} · running {running} · completed {completed} · failed {failed}{active}",
    },
    "rm_backfill_queue_active": {
        "zh": "当前正在处理：{date}",
        "en": "Currently processing: {date}",
    },
    "rm_backfill_queue_next": {
        "zh": "下一待处理日期：{date}",
        "en": "Next pending date: {date}",
    },
    "rm_last_run_at": {"zh": "上次运行完成", "en": "Last run completed"},
    "rm_clean_lock_btn": {"zh": "清理", "en": "Clean"},
    "rm_clean_lock_help": {
        "zh": "删除此已停止任务的锁文件（任务已结束，锁文件残留）",
        "en": "Remove this stale lock file (task finished, file not cleaned up)",
    },
    "rm_log_group_primary": {"zh": "系统 & 运行日志", "en": "System & Run Logs"},
    "rm_log_group_secondary": {"zh": "其他日志", "en": "Other Logs"},
    "rm_log_group_system": {"zh": "系统日志", "en": "System Logs"},
    "rm_log_group_runs": {"zh": "运行日志", "en": "Run Logs"},
    "rm_no_log_selected": {
        "zh": "请从上方选择一个日志文件以查看内容。",
        "en": "Select a log file above to view its content.",
    },
    "rm_log_file_missing": {
        "zh": "⚠️ 日志文件已不存在，可能已被清理。",
        "en": "⚠️ Log file no longer exists, it may have been cleaned up.",
    },
    "rm_scan_receipts_empty": {
        "zh": "尚无可显示的扫描收据；下一次启用持久化的日报运行后会出现。",
        "en": "No scan receipt is available yet. It will appear after the next persistent daily run.",
    },
    "rm_scan_receipts_legacy": {
        "zh": "本地数据库尚未包含扫描收据表；下一次升级后的持久化日报运行会建立可观测记录。",
        "en": "The local database does not yet contain scan receipts. A persistent daily run after the upgrade will create observable records.",
    },
    "rm_scan_receipt_candidates": {"zh": "新候选", "en": "New candidates"},
    "rm_scan_receipt_status": {"zh": "状态", "en": "Status"},
    "rm_scan_receipt_source": {"zh": "来源", "en": "Source"},
    "rm_scan_receipt_scanned_at": {"zh": "扫描时间", "en": "Scanned at"},
    "rm_health_empty": {
        "zh": "尚无可用于运行健康摘要的本地持久化数据库。",
        "en": "No local persistence database is available for operational health yet.",
    },
    "rm_health_load_error": {
        "zh": "无法读取本地运行健康摘要",
        "en": "Could not read local operational health",
    },
    "rm_health_qualification_rate": {"zh": "评分通过率", "en": "Qualification rate"},
    "rm_health_notification_backlog": {"zh": "待处理通知", "en": "Open notifications"},
    # ── proxy.py ──────────────────────────────────────────────────────
    "proxy_title": {"zh": "网络代理设置", "en": "Network Proxy Settings"},
    "proxy_enable_label": {"zh": "启用网络代理", "en": "Enable Network Proxy"},
    "proxy_url_label": {"zh": "代理地址", "en": "Proxy URL"},
    "proxy_url_help": {
        "zh": "支持 HTTP 代理（http://host:port）和 SOCKS5 代理（socks5://host:port）",
        "en": "Supports HTTP proxy (http://host:port) and SOCKS5 proxy (socks5://host:port)",
    },
    "proxy_no_proxy_label": {"zh": "不使用代理的地址", "en": "No Proxy"},
    "proxy_no_proxy_help": {
        "zh": "每行一个地址，这些地址将不使用代理",
        "en": "One address per line, these addresses will bypass the proxy",
    },
    "proxy_scope_title": {"zh": "代理范围控制", "en": "Proxy Scope Control"},
    "proxy_scope_hint": {
        "zh": "选择哪些服务使用代理。可以按需为不同服务分别启用或禁用代理。",
        "en": "Select which services use the proxy. Enable or disable proxy for each service independently.",
    },
    "proxy_arxiv_label": {"zh": "ArXiv API", "en": "ArXiv API"},
    "proxy_arxiv_help": {
        "zh": "ArXiv 论文抓取 API（export.arxiv.org）",
        "en": "ArXiv paper fetching API (export.arxiv.org)",
    },
    "proxy_openalex_label": {"zh": "OpenAlex API", "en": "OpenAlex API"},
    "proxy_openalex_help": {
        "zh": "OpenAlex 期刊论文数据源",
        "en": "OpenAlex journal paper data source",
    },
    "proxy_huggingface_papers_label": {
        "zh": "Hugging Face Papers API",
        "en": "Hugging Face Papers API",
    },
    "proxy_huggingface_papers_help": {
        "zh": "Hugging Face Papers 可选补充论文流",
        "en": "Hugging Face Papers optional supplementary feed",
    },
    "proxy_semantic_scholar_label": {
        "zh": "Semantic Scholar API",
        "en": "Semantic Scholar API",
    },
    "proxy_semantic_scholar_help": {
        "zh": "Semantic Scholar TLDR 增强功能",
        "en": "Semantic Scholar TLDR enrichment",
    },
    "proxy_llm_api_label": {"zh": "LLM API", "en": "LLM API"},
    "proxy_llm_api_help": {
        "zh": "LLM 大模型 API（评分、分析等）",
        "en": "LLM API calls (scoring, analysis, etc.)",
    },
    "proxy_notifications_label": {"zh": "通知 Webhook", "en": "Notification Webhooks"},
    "proxy_notifications_help": {
        "zh": "企业微信、钉钉、Telegram 等通知推送",
        "en": "WeChat Work, DingTalk, Telegram, and other notification pushes",
    },
    "proxy_webdav_label": {"zh": "WebDAV 同步", "en": "WebDAV Sync"},
    "proxy_webdav_help": {
        "zh": "WebDAV 配置和数据备份/恢复请求",
        "en": "WebDAV configuration and data backup/restore requests",
    },
    "proxy_update_check_label": {"zh": "检查更新", "en": "Update Check"},
    "proxy_update_check_help": {
        "zh": "GitHub 版本更新检查（需访问 api.github.com）",
        "en": "GitHub version update check (requires access to api.github.com)",
    },
    # ── data_management.py ───────────────────────────────────────────
    "tab_data_management": {"zh": "数据管理", "en": "Data Management"},
    "dm_export_title": {"zh": "配置导出", "en": "Config Export"},
    "dm_export_hint": {
        "zh": "一键打包导出 config.json 和 .env 配置文件。",
        "en": "One-click export of config.json and .env as a zip archive.",
    },
    "dm_export_btn": {"zh": "📦 导出配置", "en": "📦 Export Config"},
    "dm_export_no_files": {
        "zh": "未找到可导出的配置文件",
        "en": "No config files found to export",
    },
    "dm_export_contents": {
        "zh": "包含: config.json + .env",
        "en": "Contains: config.json + .env",
    },
    "dm_webdav_title": {"zh": "WebDAV 同步", "en": "WebDAV Sync"},
    "dm_webdav_hint": {
        "zh": "将配置和数据文件同步到 WebDAV 服务器，实现跨设备备份与恢复。默认关闭，只有启用后才会同步。",
        "en": "Sync config and data files to a WebDAV server for cross-device backup and restore. Disabled by default.",
    },
    "dm_webdav_enable": {"zh": "启用 WebDAV 同步", "en": "Enable WebDAV Sync"},
    "dm_webdav_url_label": {"zh": "WebDAV 服务器地址", "en": "WebDAV Server URL"},
    "dm_webdav_username_label": {"zh": "用户名", "en": "Username"},
    "dm_webdav_password_label": {"zh": "密码 / 应用密码", "en": "Password / App Password"},
    "dm_webdav_remote_path": {"zh": "远程存储路径", "en": "Remote Path"},
    "dm_webdav_remote_path_help": {
        "zh": "WebDAV 服务器上的存储根路径",
        "en": "Root storage path on the WebDAV server",
    },
    "dm_webdav_sync_settings": {"zh": "同步设置", "en": "Sync Settings"},
    "dm_webdav_sync_mode": {"zh": "同步模式", "en": "Sync Mode"},
    "dm_webdav_mode_manual": {"zh": "手动同步", "en": "Manual"},
    "dm_webdav_mode_scheduled": {"zh": "定时同步", "en": "Scheduled"},
    "dm_webdav_mode_after_report": {"zh": "每日报告完成后", "en": "After Daily Report"},
    "dm_webdav_sync_time": {"zh": "定时同步时间", "en": "Scheduled Sync Time"},
    "dm_webdav_sync_time_help": {
        "zh": "选择每天自动同步的时间（小时:分钟）",
        "en": "Select the daily auto-sync time (hour:minute)",
    },
    "dm_webdav_scope_title": {"zh": "同步范围", "en": "Sync Scope"},
    "dm_webdav_sync_configs_label": {"zh": "配置文件 (config.json)", "en": "Config (config.json)"},
    "dm_webdav_sync_history_label": {
        "zh": "历史数据（{database}）",
        "en": "Historical data ({database})",
    },
    "dm_webdav_sync_keywords_label": {"zh": "关键词数据 (keywords/)", "en": "Keywords (keywords/)"},
    "dm_webdav_sync_reports_label": {"zh": "报告文件 (reports/)", "en": "Reports (reports/)"},
    "dm_webdav_test_btn": {"zh": "🔌 测试连接", "en": "🔌 Test Connection"},
    "dm_webdav_upload_btn": {"zh": "⬆️ 上传同步", "en": "⬆️ Upload"},
    "dm_webdav_download_btn": {"zh": "⬇️ 下载恢复", "en": "⬇️ Download"},
    "dm_webdav_not_configured": {
        "zh": "WebDAV 未配置或未启用。请填写服务器地址和凭据。",
        "en": "WebDAV not configured or not enabled. Please fill in the server URL and credentials.",
    },
    "dm_webdav_test_ok": {"zh": "✅ WebDAV 连接成功！", "en": "✅ WebDAV connection successful!"},
    "dm_webdav_test_fail": {"zh": "❌ WebDAV 连接失败", "en": "❌ WebDAV connection failed"},
    "dm_webdav_missing_lib": {
        "zh": "❌ 缺少 webdavclient3 库。请运行: pip install webdavclient3",
        "en": "❌ Missing webdavclient3 library. Run: pip install webdavclient3",
    },
    "dm_webdav_syncing": {"zh": "正在同步...", "en": "Syncing..."},
    "dm_webdav_sync_done": {"zh": "✅ 同步完成", "en": "✅ Sync completed"},
    "dm_webdav_sync_partial": {"zh": "⚠️ 部分同步成功", "en": "⚠️ Partial sync success"},
    "dm_webdav_sync_error": {"zh": "❌ 同步失败", "en": "❌ Sync failed"},
    "dm_backup_title": {"zh": "本地备份", "en": "Local Backup"},
    "dm_backup_hint": {
        "zh": "每日运行结束后自动对 SQLite 数据库做 gzip 压缩备份：当天按数量上限保留副本（默认不限），昨天及更早每天只保留最新一份，再按下方保留期清理（默认最近 7 天；填 0 不按天数过期）；WebDAV 为增量备份，仅当数据库内容变化时上传，远端永不删除；也可手动立即备份。",
        "en": "After each daily run a gzip-compressed SQLite backup is created automatically: current-day copies follow the optional count limit (unlimited by default), while each earlier day keeps only its newest copy before the retention window is applied (7 days by default; 0 disables age expiry); WebDAV mirrors incrementally — uploads happen only when the database content changed and remote copies are never deleted. Manual backup is also available.",
    },
    "dm_backup_enable": {"zh": "启用自动备份", "en": "Enable automatic backup"},
    "dm_backup_retention_days_label": {
        "zh": "本地备份保留天数",
        "en": "Local backup retention (days)",
    },
    "dm_backup_retention_days_help": {
        "zh": "自动删除早于此天数的本地 SQLite 备份；昨天及更早每天只留最新一份。默认 7 天，填 0 不按天数过期。WebDAV 增量归档不受此设置影响。",
        "en": "Automatically delete local SQLite backups older than this many days. Each earlier day keeps only its newest copy. Default: 7; enter 0 to disable age expiry. WebDAV incremental archives are unaffected.",
    },
    "dm_backup_same_day_max_label": {
        "zh": "当天备份最多保留数量",
        "en": "Maximum current-day backups",
    },
    "dm_backup_same_day_max_help": {
        "zh": "仅限制当天的本地 SQLite 备份。填 0 保留当天全部备份；正整数保留最新的 N 个。昨天及更早每天只留最新一份。",
        "en": "Limits only local SQLite backups created today. Enter 0 to keep all of them; a positive number keeps the newest N. Each earlier day keeps only its newest copy.",
    },
    "dm_backup_now_btn": {"zh": "🗄️ 立即备份", "en": "🗄️ Back Up Now"},
    "dm_backup_export_btn": {"zh": "📤 生成导出（zip）", "en": "📤 Build export (zip)"},
    "dm_backup_download_btn": {"zh": "⬇️ 下载备份压缩包", "en": "⬇️ Download backup archive"},
    "dm_backup_import_label": {"zh": "导入备份（zip / gz / db）", "en": "Import backup (zip / gz / db)"},
    "dm_backup_import_btn": {"zh": "📥 导入并覆盖当前数据库", "en": "📥 Import and replace current database"},
    "dm_backup_import_ok": {"zh": "导入成功（来源：{source}）；原数据库已存档：{archived}", "en": "Imported (source: {source}); previous database archived at: {archived}"},
    "dm_backup_existing": {"zh": "现有备份", "en": "Existing backups"},
    "dm_backup_none": {"zh": "暂无备份。运行一次每日研究或点击上方按钮即可生成。", "en": "No backups yet. Run the daily research once or use the button above."},
    "dm_backup_col_name": {"zh": "文件名", "en": "File"},
    "dm_backup_col_size": {"zh": "大小", "en": "Size"},
    "dm_backup_col_time": {"zh": "时间", "en": "Time"},
    "dm_backup_running": {"zh": "正在创建压缩备份...", "en": "Creating compressed backup..."},
    "dm_backup_done_local": {"zh": "✅ 备份完成（仅本地）", "en": "✅ Backup created (local only)"},
    "dm_backup_done_uploaded": {"zh": "✅ 备份完成并已上传 WebDAV", "en": "✅ Backup created and uploaded to WebDAV"},
    "dm_backup_done_unchanged": {
        "zh": "✅ 本地备份完成；WebDAV 内容未变化，已跳过上传（远端副本保留）",
        "en": "✅ Local backup created; WebDAV content unchanged, upload skipped (remote copy kept)",
    },
    "dm_backup_done_upload_failed": {
        "zh": "⚠️ 本地备份已完成，但 WebDAV 上传失败：{}",
        "en": "⚠️ Local backup created, but the WebDAV upload failed: {}",
    },
    "dm_backup_local_only": {
        "zh": "WebDAV 凭据不完整，本次仅做本地备份",
        "en": "WebDAV credentials incomplete; backing up locally only",
    },
    "dm_backup_skip_reason": {"zh": "未创建备份：{}", "en": "Backup not created: {}"},
    "dm_backup_failed": {"zh": "❌ 备份失败", "en": "❌ Backup failed"},
    # 旧版本（v3.2）历史导入
    "dm_legacy_title": {"zh": "旧版本历史导入（v3.2）", "en": "Legacy History Import (v3.2)"},
    "dm_history_task_list_title": {"zh": "历史维护任务", "en": "History Maintenance Tasks"},
    "dm_history_task_list_hint": {
        "zh": "显示由 Web 面板提交的导入、数据补全和遗漏扫描任务。任务会在相关工作空闲后自动执行；失败与中断任务可直接重新加入队列。",
        "en": "Shows imports, data repairs, and omission scans submitted from the WebUI. Tasks start when related work is idle; failed or interrupted tasks can be queued again here.",
    },
    "dm_history_task_list_empty": {"zh": "尚无历史维护任务记录。", "en": "No history-maintenance task has been recorded yet."},
    "dm_task_legacy_import": {"zh": "旧历史导入", "en": "Legacy history import"},
    "dm_task_history_repair": {"zh": "历史数据补全", "en": "Historical data repair"},
    "dm_task_history_omission": {"zh": "历史遗漏扫描", "en": "Historical omission scan"},
    "dm_task_unknown": {"zh": "未知任务", "en": "Unknown task"},
    "dm_task_col_name": {"zh": "任务", "en": "Task"},
    "dm_task_col_state": {"zh": "状态", "en": "State"},
    "dm_task_col_progress": {"zh": "进度", "en": "Progress"},
    "dm_task_col_started": {"zh": "开始时间", "en": "Started"},
    "dm_task_col_completed": {"zh": "完成时间", "en": "Completed"},
    "dm_task_col_issue": {"zh": "问题摘要", "en": "Issue summary"},
    "dm_task_state_queued": {"zh": "等待空闲", "en": "Queued"},
    "dm_task_state_starting": {"zh": "启动中", "en": "Starting"},
    "dm_task_state_running": {"zh": "运行中", "en": "Running"},
    "dm_task_state_succeeded": {"zh": "已完成", "en": "Succeeded"},
    "dm_task_state_failed": {"zh": "失败", "en": "Failed"},
    "dm_task_state_rejected": {"zh": "已拒绝", "en": "Rejected"},
    "dm_task_state_interrupted": {"zh": "已中断", "en": "Interrupted"},
    "dm_task_state_skipped_busy": {"zh": "因冲突跳过", "en": "Skipped (busy)"},
    "dm_task_progress_queued": {"zh": "等待其他任务空闲", "en": "Waiting for related work to become idle"},
    "dm_task_progress_starting": {"zh": "已被工作进程接手", "en": "Claimed by worker"},
    "dm_task_progress_running": {"zh": "正在执行", "en": "In progress"},
    "dm_task_progress_waiting_idle": {"zh": "等待相关任务空闲或初始化", "en": "Waiting for related work to become idle or initialize"},
    "dm_task_progress_terminal": {"zh": "已结束", "en": "Finished"},
    "dm_task_issue_busy": {"zh": "运行锁冲突，任务未执行", "en": "A run lock was active; this task did not execute"},
    "dm_task_retry_hint": {"zh": "失败、中断或因冲突跳过的任务可重试：", "en": "Retry failed, interrupted, or busy-skipped tasks:"},
    "dm_task_retry_btn": {"zh": "重试", "en": "Retry"},
    "dm_legacy_hint": {
        "zh": "旧 HTML 报告会按来源解析为 SQLite 历史账本；同一论文会通过 DOI 或精确 arXiv 版本归并为一个论文实体。重复卡片以最新报告为准；所有维护任务均会等待每日研究、补充报告、过去日报和趋势分析空闲后执行。",
        "en": "Legacy HTML reports are indexed by source into the SQLite history ledger. The same work is linked into one paper entity through a DOI or an exact arXiv version. Duplicate cards use the newest report. Every maintenance task waits for daily research, supplements, backfills, and trend work to become idle.",
    },
    "dm_legacy_full_repair_toggle": {
        "zh": "完整修复旧历史",
        "en": "Fully repair legacy history",
    },
    "dm_legacy_full_repair_help": {
        "zh": "关闭时登记旧 HTML 中已有的各来源论文，避免后续日报重复处理。开启时读取旧 JSON、补全缺失字段、扫描遗漏论文并生成补充报告；旧 keywords.db 只会为同一 HTML 论文补齐缺失关键词。",
        "en": "Off: index papers already present in legacy HTML for every source so future runs do not repeat them. On: read legacy JSON, repair missing fields, scan omissions, and generate supplements; old keywords.db only fills a missing keyword section for the same HTML paper.",
    },
    "dm_legacy_full_repair_off_hint": {
        "zh": "轻量建账：不调用 LLM、不读取旧 JSON 或旧关键词库、不扫描遗漏论文。",
        "en": "Lightweight indexing: no LLM calls, legacy JSON/keyword-cache reads, or omission scan.",
    },
    "dm_legacy_full_repair_on_hint": {
        "zh": "完整修复：读取旧 JSON；报告关键词以 HTML 为准，旧 keywords.db 仅补齐同一报告中缺失的关键词。随后自动补全 SQLite 字段、修补原报告，并按自然周生成遗漏论文补充报告。",
        "en": "Full repair reads legacy JSON. HTML remains authoritative for report keywords; old keywords.db only fills a missing keyword section for the same report. It then repairs SQLite fields and original reports, and creates omission supplements by calendar week.",
    },
    "dm_legacy_mode_light": {"zh": "轻量建账", "en": "Lightweight indexing"},
    "dm_legacy_mode_full": {"zh": "完整修复", "en": "Full repair"},
    "dm_legacy_import_btn": {"zh": "📜 读取旧历史", "en": "📜 Read Legacy History"},
    "dm_history_maintenance_title": {"zh": "历史数据维护", "en": "Historical Data Maintenance"},
    "dm_history_repair_btn": {"zh": "🩹 检查并补全历史数据", "en": "🩹 Check and Repair History"},
    "dm_history_omission_btn": {"zh": "🗓️ 扫描遗漏并生成补充报告", "en": "🗓️ Scan Omissions and Build Supplements"},
    "dm_history_repair_queued": {"zh": "已加入队列：空闲后检查并补全历史数据。", "en": "Queued: historical data will be checked and repaired when idle."},
    "dm_history_omission_queued": {"zh": "已加入队列：空闲后扫描遗漏并按自然周生成补充报告。", "en": "Queued: omissions will be scanned and supplemented by calendar week when idle."},
    "dm_history_repair_short": {"zh": "历史数据补全", "en": "history repair"},
    "dm_history_omission_short": {"zh": "历史遗漏扫描", "en": "omission scan"},
    "dm_history_task_running_hint": {"zh": "{tasks} 正在排队或运行中，请在本页任务和状态面板或“系统 → 日志”查看进度。", "en": "{tasks} is queued or running. Follow their progress in this page's task/status panel or System → Run Logs."},
    "dm_supplement_btn": {"zh": "🧾 生成补充报告", "en": "🧾 Build Supplement Report"},
    "dm_supplement_help": {
        "zh": "把补充积压中的论文（缺数据/遗漏）按「本次最多处理论文数」重跑评分/翻译/分析并生成一份补充报告；会消耗 LLM 额度，任务在空闲时自动运行。",
        "en": "Re-run the backlogged papers (incomplete/missed) through scoring/translation/analysis, capped by max papers per run, into one supplement report; consumes LLM quota and starts when idle.",
    },
    "dm_supplement_queued": {
        "zh": "已加入触发队列：worker 空闲时自动生成补充报告。",
        "en": "Queued: the worker will build the supplement report when idle.",
    },
    "dm_legacy_queued": {
        "zh": "已加入触发队列：worker 空闲时自动读取旧历史，并按当前完整修复开关执行后续维护。",
        "en": "Queued: the worker will import legacy history when idle and follow the selected full-repair setting.",
    },
    "dm_legacy_running_hint": {
        "zh": "旧历史导入流程正在排队或运行中，请在本页任务和状态面板或“系统 → 日志”查看实时进度。",
        "en": "The legacy-import workflow is queued or running. Follow its progress in this page's task/status panel or System → Run Logs.",
    },
    "dm_legacy_failed": {"zh": "❌ 触发失败", "en": "❌ Failed to queue"},
    "dm_legacy_none": {
        "zh": "尚未导入过旧历史。",
        "en": "Legacy history has not been imported yet.",
    },
    "dm_history_status_title": {"zh": "状态面板", "en": "Status Panel"},
    "dm_history_auto_refresh_help": {
        "zh": "开启后，仅在历史导入、数据补全或遗漏扫描排队、启动和运行期间每 5 秒刷新；任务结束后自动停止刷新。",
        "en": "When enabled, this panel refreshes every 5 seconds only while a history import, repair, or omission scan is queued, starting, or running. It stops automatically after work finishes.",
    },
    "dm_history_status_idle": {
        "zh": "当前没有进行中的历史维护任务。",
        "en": "No history-maintenance task is currently running.",
    },
    "dm_history_status_attention": {
        "zh": "有 {count} 个历史维护任务需要处理或重试。",
        "en": "{count} history-maintenance task(s) need attention or retry.",
    },
    "dm_history_status_started": {"zh": "开始时间：{started}", "en": "Started: {started}"},
    "dm_history_pending_title": {"zh": "未完成任务", "en": "Unfinished Tasks"},
    "dm_history_pending_empty": {
        "zh": "当前没有未完成的历史维护任务。",
        "en": "There are no unfinished history-maintenance tasks.",
    },
    "dm_legacy_summary_title": {"zh": "最近一次导入结果", "en": "Last import result"},
    "dm_history_summary_meta": {
        "zh": "完成时间：{finished} · 模式：{mode}",
        "en": "Finished: {finished} · mode: {mode}",
    },
    "dm_history_summary_reports": {"zh": "报告", "en": "Reports"},
    "dm_history_summary_cards": {"zh": "论文卡片", "en": "Paper cards"},
    "dm_history_summary_delivered": {"zh": "交付记录", "en": "Deliveries"},
    "dm_history_summary_backlog": {"zh": "待补充", "en": "Backlog"},
    "dm_history_summary_missing": {
        "zh": "发现缺失：卡片 {cards} · TL;DR {tldr} · 翻译 {translation} · 分析 {analysis}",
        "en": "Missing data: cards {cards} · TL;DR {tldr} · translations {translation} · analyses {analysis}",
    },
    "dm_legacy_summary_line": {
        "zh": "{finished} · {mode} · 报告 {reports} 份 · 卡片 {cards} 张 · 交付账本 {delivered} 条 · 缺卡片 {missing_cards} · 缺 TL;DR {missing_tldr} · 缺翻译 {missing_translation} · 缺分析 {missing_analysis} · 积压 {backlog} 条",
        "en": "{finished} · {mode} · {reports} reports · {cards} cards · {delivered} deliveries · missing cards {missing_cards} · missing TL;DR {missing_tldr} · missing translations {missing_translation} · missing analyses {missing_analysis} · backlog {backlog}",
    },
    "dm_legacy_source_breakdown": {
        "zh": "已登记来源：{sources}",
        "en": "Indexed sources: {sources}",
    },
    "dm_legacy_supplement_line": {
        "zh": "自动补充报告：{state} · 本次处理 {processed} 篇 · 剩余积压 {pending} 条",
        "en": "Automatic supplement: {state} · processed {processed} papers · backlog remaining {pending}",
    },
    "dm_report_keywords_line": {
        "zh": "报告关键词：{state} · HTML {html_papers} 篇 / {html_terms} 个 · 旧库补齐 {fallback_papers} 篇 / {fallback_terms} 个",
        "en": "Report keywords: {state} · HTML {html_papers} papers / {html_terms} terms · old-cache fallback {fallback_papers} papers / {fallback_terms} terms",
    },
    "dm_report_keywords_state_html_only": {"zh": "仅 HTML", "en": "HTML only"},
    "dm_report_keywords_state_not_needed": {"zh": "HTML 已完整", "en": "complete in HTML"},
    "dm_report_keywords_state_supplemented": {"zh": "按报告补齐", "en": "report-scoped fallback used"},
    "dm_report_keywords_state_no_matching": {"zh": "旧库无匹配记录", "en": "no matching cache records"},
    "dm_report_keywords_state_not_found": {"zh": "未找到旧库", "en": "legacy cache not found"},
    "dm_report_keywords_state_not_configured": {"zh": "未配置旧库", "en": "legacy cache not configured"},
    "dm_report_keywords_state_unreadable": {"zh": "旧库无法读取", "en": "legacy cache unreadable"},
    "dm_report_keywords_state_unsupported": {"zh": "旧库格式不支持", "en": "legacy cache schema unsupported"},
    "dm_report_keywords_legacy_summary": {
        "zh": "旧版关键词库迁移记录保留；下次导入起仅使用 HTML 报告关键词。",
        "en": "The previous keyword-cache migration record is retained; future imports use report-scoped HTML keywords only.",
    },
    "dm_history_repair_line": {
        "zh": "历史数据补全：{state} · 检查 {candidates} 篇 · TL;DR {tldr} · 翻译 {translation} · 分析 {analysis} · 待重试 {pending}",
        "en": "History repair: {state} · checked {candidates} · TL;DR {tldr} · translations {translation} · analyses {analysis} · retry pending {pending}",
    },
    "dm_history_omission_line": {
        "zh": "历史遗漏扫描：{state} · 发现 {found} 篇 · 自然周 {weeks} 个 · 待处理 {pending}",
        "en": "History omission scan: {state} · found {found} · weeks {weeks} · pending {pending}",
    },
    "dm_legacy_backlog_title": {"zh": "补充运行积压", "en": "Supplement backlog"},
    "dm_legacy_backlog_line": {
        "zh": "待处理 {pending} 条（缺数据 {missing} · 遗漏 {missed}）；下次完整修复或对应维护任务会继续重试",
        "en": "{pending} pending ({missing} incomplete · {missed} missed); the next full repair or matching maintenance task will retry them",
    },
    "ps_title": {"zh": "论文检索", "en": "Paper Search"},
    "ps_hint": {"zh": "在已处理论文的标题、作者、摘要、TLDR 与提取关键词中检索；同一论文的多来源记录会归并展示。", "en": "Search titles, authors, abstracts, TLDRs and extracted keywords of processed papers; records for the same work are grouped across sources."},
    "ps_query_label": {"zh": "检索词", "en": "Query"},
    "ps_query_placeholder": {
        "zh": "例如：diffusion model、作者名、关键词……",
        "en": "e.g. diffusion model, an author name, a keyword...",
    },
    "ps_source_label": {"zh": "来源", "en": "Source"},
    "ps_source_all": {"zh": "全部来源", "en": "All sources"},
    "ps_date_label": {"zh": "处理日期范围", "en": "Processed date range"},
    "ps_date_help": {
        "zh": "可选；按论文被处理入库的日期过滤",
        "en": "Optional; filters by the date the paper was processed",
    },
    "ps_min_score_label": {"zh": "最低总分", "en": "Minimum score"},
    "ps_min_score_help": {
        "zh": "0 表示不过滤；按历史评分总分过滤",
        "en": "0 disables the filter; uses the historical total score",
    },
    "ps_liked_only_label": {"zh": "只看收藏 (👍)", "en": "Liked only (👍)"},
    "ps_search_btn": {"zh": "🔍 检索", "en": "🔍 Search"},
    "ps_idle_hint": {"zh": "输入条件后点击检索。留空检索词可只用过滤器浏览全库。", "en": "Enter criteria and click Search. An empty query lists the whole archive with filters."},
    "ps_result_title": {"zh": "共 {total} 篇匹配", "en": "{total} matching papers"},
    "ps_no_match": {"zh": "没有匹配的论文。", "en": "No matching papers."},
    "ps_no_data": {"zh": "暂无数据库或尚未处理任何论文。", "en": "No database yet, or no papers processed."},
    "ps_search_failed": {"zh": "检索失败：{}", "en": "Search failed: {}"},
    "ps_col_source": {"zh": "来源", "en": "Source"},
    "ps_col_sources": {"zh": "来源", "en": "Sources"},
    "ps_col_completed": {"zh": "处理时间", "en": "Processed"},
    "ps_col_published": {"zh": "发表日期", "en": "Published"},
    "ps_col_strategy": {"zh": "评分策略", "en": "Strategy"},
    "ps_col_authors": {"zh": "作者", "en": "Authors"},
    "ps_col_keywords": {"zh": "提取关键词", "en": "Extracted keywords"},
    "ps_merged_keywords": {"zh": "合并关键词", "en": "Merged keywords"},
    "ps_variants_title": {"zh": "各来源处理记录", "en": "Source-specific records"},
    "ps_variant_title": {"zh": "{source} · 处理于 {completed}", "en": "{source} · processed {completed}"},
    "ps_variant_score_status": {"zh": "评分", "en": "Score"},
    "ps_variant_translation_status": {"zh": "翻译", "en": "Translation"},
    "ps_variant_analysis_status": {"zh": "分析", "en": "Analysis"},
    "ps_variant_translation": {"zh": "摘要翻译", "en": "Abstract translation"},
    "ps_variant_keywords": {"zh": "该来源关键词", "en": "Source keywords"},
    "ps_variant_analysis": {"zh": "深度分析", "en": "Deep analysis"},
    "ps_variant_error": {"zh": "最近错误", "en": "Latest error"},
    "ps_variant_report_path": {"zh": "报告文件：{path}", "en": "Report file: {path}"},
    "ps_col_categories": {"zh": "分类", "en": "Categories"},
    "ps_link_abs": {"zh": "论文页", "en": "Abstract"},
    "ps_link_pdf": {"zh": "PDF", "en": "PDF"},
    "ps_prev_page": {"zh": "← 上一页", "en": "← Previous"},
    "ps_next_page": {"zh": "下一页", "en": "Next"},
    "ps_page_info": {"zh": "第 {page} / {pages} 页", "en": "Page {page} of {pages}"},
    "sh_title": {"zh": "数据源健康", "en": "Source Health"},
    "sh_no_data": {"zh": "暂无数据库，运行一次每日研究后可见。", "en": "No database yet; visible after the first daily research run."},
    "sh_no_receipts": {"zh": "尚无扫描收据。运行一次每日研究后可见。", "en": "No scan receipts yet; visible after the first daily research run."},
    "sh_load_failed": {"zh": "健康数据加载失败：{}", "en": "Failed to load health data: {}"},
    "sh_success_rate": {"zh": "成功率", "en": "Success"},
    "sh_success_rate_help": {"zh": "最近 20 次扫描中成功终态的占比", "en": "Succeeded terminal scans out of the last 20"},
    "sh_new_candidates": {"zh": "最近新增", "en": "New papers"},
    "sh_new_candidates_help": {"zh": "最近一次成功扫描新入队的候选论文数", "en": "Candidates newly queued by the newest successful scan"},
    "sh_last_scan": {"zh": "最近扫描：{time}", "en": "Last scan: {time}"},
    "sh_last_error": {"zh": "最近一次错误", "en": "Newest error"},
    "sh_window_note": {"zh": "共汇总 {scans} 条扫描收据（每个来源最近 20 次）。", "en": "Summarized {scans} scan receipts (last 20 per source)."},
    "sh_col_source": {"zh": "来源", "en": "Source"},
    "sh_col_latest": {"zh": "最近请求", "en": "Latest request"},
    "sh_col_status": {"zh": "最新状态", "en": "Latest status"},
    "sh_col_task": {"zh": "最近任务", "en": "Latest task"},
    "sh_col_requests": {"zh": "成功/请求", "en": "Succeeded / requests"},
    "sh_col_success_rate": {"zh": "成功率", "en": "Success rate"},
    "sh_col_candidates": {"zh": "最近新增", "en": "Latest new papers"},
    "sh_col_last_error": {"zh": "最近失败信息（已脱敏）", "en": "Latest failure (redacted)"},
    "health_task_daily": {"zh": "每日研究", "en": "Daily research"},
    "health_task_backfill": {"zh": "过去日报", "en": "Past-date report"},
    "health_task_history_import": {"zh": "旧历史导入", "en": "Legacy history import"},
    "health_task_history_repair": {"zh": "历史数据补全", "en": "History data repair"},
    "health_task_history_omission": {"zh": "历史遗漏扫描", "en": "History omission scan"},
    "health_task_supplement": {"zh": "补充报告", "en": "Supplement report"},
    "health_task_trend": {"zh": "趋势研究", "en": "Trend research"},
    "learned_strategy_info": {"zh": "学习模式：在旧版加权总分之上叠加学习库修正。学习库来自你的收藏/不喜欢与 v1 及格历史，学到的权重有上限且始终低于直接配置的评分关键词。", "en": "Learned mode adds a learned-library adjustment on top of the legacy weighted score. The library learns from your likes/dislikes and legacy v1 passes; learned weights are capped so they always matter less than directly configured keywords."},
    "learned_weight_dampening_label": {"zh": "学习权重衰减系数", "en": "Learned weight dampening"},
    "learned_weight_dampening_help": {
        "zh": "0-1；学习到的权重统一乘以该系数，越小学习项影响越弱",
        "en": "0-1; learned weights are scaled by this factor; smaller means weaker influence",
    },
    "learned_term_weight_cap_label": {"zh": "学习单项限幅", "en": "Learned term weight cap"},
    "learned_term_weight_cap_help": {
        "zh": "单个学习关键词/作者的最大绝对权重，超出按此截断",
        "en": "Maximum absolute weight of a single learned keyword/author",
    },
    "learned_library_keywords": {"zh": "学习关键词库", "en": "Learned keywords"},
    "learned_library_authors": {"zh": "学习作者库", "en": "Learned authors"},
    "learned_term_col_term": {"zh": "词条", "en": "Term"},
    "learned_term_col_weight": {"zh": "权重", "en": "Weight"},
    "learned_library_empty": {
        "zh": "学习库为空：标记收藏/不喜欢或运行几次 v1 评分后，这里会逐步出现带权重的关键词与作者。",
        "en": "The learned library is empty: mark likes/dislikes or run a few v1-scored days and weighted keywords/authors will accumulate here.",
    },
    "learned_library_note": {
        "zh": "权重 = 收藏(+1)/不喜欢(-1)/v1 及格(+0.25) 信号之和；评分时按限幅与衰减生效。",
        "en": "Weight = sum of like(+1)/dislike(-1)/v1-pass(+0.25) signals; applied with the cap and dampening at scoring time.",
    },
}
